<?php
// Error Levels Desciption
$locale['E_ERROR'] = "Fatal Errors halting script execution";
$locale['E_WARNING'] = "Non fatal runtime errors";
$locale['E_PARSE'] = "Error generated by parser";
$locale['E_NOTICE'] = "Run-time notices";
$locale['E_CORE_ERROR'] = "Error during PHP's initial startup";
$locale['E_CORE_WARNING'] = "PHP startup warning";
$locale['E_COMPILE_ERROR'] = "Zend warning";
$locale['E_COMPILE_WARNING'] = "Parser warning";
$locale['E_USER_ERROR'] = "trigger_error() generated warning";
$locale['E_USER_WARNING'] = "trigger_error() generated warning";
$locale['E_USER_NOTICE'] = "trigger_error() generated notice";
$locale['E_ALL'] = "Defines all messages except E_STRICT";
$locale['E_STRICT'] = "PHP compatibality warning";

$locale['_E_ERROR'] = "A fatal run-time error, that can't be recovered from. The execution of the script is stopped immediately.";
$locale['_E_WARNING'] = "A run-time warning. It is non-fatal and most errors tend to fall into this category. The execution of the script is not stopped.";
$locale['_E_PARSE'] = "The compile-time parse error. Parse errors should only be generated by the parser.";
$locale['_E_NOTICE'] = "A run-time notice indicating that the script encountered something that could possibly an error, although the situation could also occur when running a script normally.";
$locale['_E_CORE_ERROR'] = "A fatal error that occur during the PHP's engine initial startup. This is like an E_ERROR, except it is generated by the core of PHP.";
$locale['_E_CORE_WARNING'] = "	A non-fatal error that occur during the PHP's engine initial startup. This is like an E_WARNING, except it is generated by the core of PHP.";
$locale['_E_COMPILE_ERROR'] = "A fatal error that occur while the script was being compiled. This is like an E_ERROR, except it is generated by the Zend Scripting Engine.";
$locale['_E_COMPILE_WARNING'] = "A non-fatal error occur while the script was being compiled. This is like an E_WARNING, except it is generated by the Zend Scripting Engine.";
$locale['_E_USER_ERROR'] = "A fatal user-generated error message. This is like an E_ERROR, except it is generated by the PHP code using the function trigger_error() rather than the PHP engine.";
$locale['_E_USER_WARNING'] = "A non-fatal user-generated warning message. This is like an E_WARNING, except it is generated by the PHP code using the function trigger_error() rather than the PHP engine";
$locale['_E_USER_NOTICE'] = "A user-generated notice message. This is like an E_NOTICE, except it is generated by the PHP code using the function trigger_error() rather than the PHP engine.";
$locale['_E_ALL'] = "Defines all messages except E_STRICT";
$locale['_E_STRICT'] = "Not strictly an error, but triggered whenever PHP encounters code that could lead to problems or forward incompatibilities";
$locale['_E_RECOVERABLE_ERROR'] = "A catchable fatal error. Although the error was fatal, it did not leave the PHP engine in an unstable state. If the error is not caught by a user defined error handler (see set_error_handler()), the application aborts as it was an E_ERROR.";
$locale['_E_DEPRECATED'] = "A run-time notice indicating that the code will not work in future versions of PHP";
$locale['_E_USER_DEPRECATED'] = "A user-generated warning message. This is like an E_DEPRECATED, except it is generated by the PHP code using the function trigger_error() rather than the PHP engine.";
$locale['_E_ALL'] = "All errors and warnings, except of level E_STRICT prior to PHP 5.4.0.";


$locale['err_100'] = "N/A";
$locale['err_101'] = "WARNING: An error occurred while parsing the page. Please see PHPFusion's [ERROR_LOG_URL]Error Log[/ERROR_LOG_URL] for more details.";
$locale['err_102'] = "Show me the bug!";
$locale['err_103'] = "{%function%} {%folder%} does not exists.";
