<?php
// Error Levels Desciption
$locale['E_ERROR'] = "Błąd krytyczny, zatrzymano wykonywanie skryptu/Fatal Errors halting script execution";
$locale['E_WARNING'] = "Błąd niekrytyczny, kontynuowano wykonywanie skryptu/Non fatal Runtime Errors";
$locale['E_PARSE'] = "Błąd składni PHP/Error generated by parser";
$locale['E_NOTICE'] = "Zdarzenie mogące być błędem/Run-time notices";
$locale['E_CORE_ERROR'] = "Błąd krytyczny podczas uruchomienia PHP/Error during PHP's initial startup";
$locale['E_CORE_WARNING'] = "Błąd niekrytyczny podczas uruchomienia PHP/Warning during PHP's initial startup";
$locale['E_COMPILE_ERROR'] = "Błąd krytyczny zgłoszony przez Zend Engine/Warning generated by zend";
$locale['E_COMPILE_WARNING'] = "Błąd niekrytyczny zgłoszony przez parser/Error generated by parser";
$locale['E_USER_ERROR'] = "Błąd krytyczny zgłoszony przez funkcję trigger_error()/Error generated by user using trigger_error() function";
$locale['E_USER_WARNING'] = "Błąd niekrytyczny zgłoszony przez funkcję trigger_error()/Warning generated by user using trigger_error() function";
$locale['E_USER_NOTICE'] = "Informacja zgłoszona przez funkcję trigger_error()/Notice generated by user using trigger_error() function";
$locale['E_ALL'] = "Pokazuje wszystkie wiadomości poza E_STRICT/Defines all messages except E_STRICT";
$locale['E_STRICT'] = "";
$locale['err_100'] = "Nd.";
$locale['err_101'] = "<strong>Ostrzeżenie:</strong> W trakcie generowania strony wystąpił błąd. Sprawdź <a href='[ERROR_LOG_URL]'>dziennik błędów</a>, aby uzyskać więcej informacji.";
$locale['err_102'] = "Pokaż mi błąd!";
