<?php
const BASEDIR = __DIR__.DIRECTORY_SEPARATOR;
define("ADMIN", BASEDIR."administration".DIRECTORY_SEPARATOR);
define("CLASSES", BASEDIR."includes".DIRECTORY_SEPARATOR."classes".DIRECTORY_SEPARATOR);
define("CONTENTS", BASEDIR."contents".DIRECTORY_SEPARATOR);
define("ADMIN_CONTENTS", BASEDIR."contents".DIRECTORY_SEPARATOR."admin".DIRECTORY_SEPARATOR);
define("DYNAMICS", BASEDIR."includes".DIRECTORY_SEPARATOR."dynamics".DIRECTORY_SEPARATOR);
define("INFUSIONS", BASEDIR."infusions".DIRECTORY_SEPARATOR);
define("IMAGES", BASEDIR."images".DIRECTORY_SEPARATOR);
define("INCLUDES", BASEDIR."includes".DIRECTORY_SEPARATOR);
define("LOCALE", BASEDIR."locale".DIRECTORY_SEPARATOR);
define("THEMES", BASEDIR."themes".DIRECTORY_SEPARATOR);
define("TEMPLATES", BASEDIR."themes".DIRECTORY_SEPARATOR."templates".DIRECTORY_SEPARATOR);
define("DB_HANDLERS", BASEDIR."includes".DIRECTORY_SEPARATOR."db_handlers".DIRECTORY_SEPARATOR);
define("WIDGETS", BASEDIR."widgets".DIRECTORY_SEPARATOR);
