<?php
// Titles
$locale['ERROR_400'] = "Error Log";
$locale['ERROR_401'] = "Take a look into the file";
// Errors table
$locale['ERROR_410'] = "Error";
$locale['ERROR_411'] = "On Page";
$locale['ERROR_412'] = "User";
$locale['ERROR_413'] = "Date";
$locale['ERROR_414'] = "Status";
$locale['ERROR_415'] = "Line:";
$locale['ERROR_416'] = "Level:";
$locale['ERROR_417'] = "IP:";
$locale['ERROR_418'] = "No errors in the log.";
$locale['ERROR_419'] = "File";
$locale['ERROR_420'] = "Details";
$locale['ERROR_421'] = "Source code";
$locale['ERROR_422'] = "Back to top";
// Delete form
$locale['ERROR_440'] = "Delete all entries with status";
// Status form
$locale['ERROR_450'] = "New";
$locale['ERROR_451'] = "Solved";
$locale['ERROR_452'] = "Ignored";
$locale['ERROR_453'] = "Apply";
$locale['ERROR_454'] = "Severity";

$locale['ERROR_460'] = "Errors";
$locale['ERROR_461'] = "Error File";
$locale['ERROR_462'] = "Options";
$locale['ERROR_463'] = "Generated by";
$locale['ERROR_464'] = "Error Console";
$locale['ERROR_465'] = "Source File";
