<?php
// Titles
$locale['400'] = "Error Log";
$locale['401'] = "Take a look into the file";
// Tabs
$locale['402'] = "Errors";
$locale['403'] = "Error File";
$locale['404'] = "Source File";
// Errors table
$locale['410'] = "Error";
$locale['411'] = "On Page";
$locale['412'] = "User";
$locale['413'] = "Date";
$locale['414'] = "Status";
$locale['415'] = "Line:";
$locale['416'] = "Level:";
$locale['417'] = "IP:";
$locale['418'] = "No errors in the log.";
$locale['419'] = "File";
$locale['420'] = "Details";
$locale['421'] = "Source code";
$locale['422'] = "Back to top";
$locale['423'] = "generated by";
$locale['424'] = "Options";
$locale['425'] = "Error Console";
// Delete form
$locale['440'] = "Delete all entries with status";
// Status form
$locale['450'] = "New";
$locale['451'] = "Solved";
$locale['452'] = "Ignored";
$locale['453'] = "Apply";
$locale['454'] = "Severity";
