<?php
/*-------------------------------------------------------+
| PHPFusion Content Management System
| Copyright (C) PHP Fusion Inc
| https://phpfusion.com/
+--------------------------------------------------------+
| Filename: callingcodes.inc.php
| Author: Frederick MC CHan (Chan)
+--------------------------------------------------------+
| This program is released as free software under the
| Affero GPL license. You can redistribute it and/or
| modify it under the terms of this license which you
| can read by viewing the included agpl.txt or online
| at www.gnu.org/licenses/agpl.html. Removal of this
| copyright header is strictly prohibited without
| written permission from the original author(s).
+--------------------------------------------------------*/

$countries[] = ["code" => "AF", "name" => "Afghanistan", "prefix" => "+93"];
$countries[] = ["code" => "AL", "name" => "Albania", "prefix" => "+355"];
$countries[] = ["code" => "DZ", "name" => "Algeria", "prefix" => "+213"];
$countries[] = ["code" => "AS", "name" => "American Samoa", "prefix" => "+1"];
$countries[] = ["code" => "AD", "name" => "Andorra", "prefix" => "+376"];
$countries[] = ["code" => "AO", "name" => "Angola", "prefix" => "+244"];
$countries[] = ["code" => "AI", "name" => "Anguilla", "prefix" => "+1"];
$countries[] = ["code" => "AG", "name" => "Antigua", "prefix" => "+1"];
$countries[] = ["code" => "AR", "name" => "Argentina", "prefix" => "+54"];
$countries[] = ["code" => "AM", "name" => "Armenia", "prefix" => "+374"];
$countries[] = ["code" => "AW", "name" => "Aruba", "prefix" => "+297"];
$countries[] = ["code" => "AU", "name" => "Australia", "prefix" => "+61"];
$countries[] = ["code" => "AT", "name" => "Austria", "prefix" => "+43"];
$countries[] = ["code" => "AZ", "name" => "Azerbaijan", "prefix" => "+994"];
$countries[] = ["code" => "BH", "name" => "Bahrain", "prefix" => "+973"];
$countries[] = ["code" => "BD", "name" => "Bangladesh", "prefix" => "+880"];
$countries[] = ["code" => "BB", "name" => "Barbados", "prefix" => "+1"];
$countries[] = ["code" => "BY", "name" => "Belarus", "prefix" => "+375"];
$countries[] = ["code" => "BE", "name" => "Belgium", "prefix" => "+32"];
$countries[] = ["code" => "BZ", "name" => "Belize", "prefix" => "+501"];
$countries[] = ["code" => "BJ", "name" => "Benin", "prefix" => "+229"];
$countries[] = ["code" => "BM", "name" => "Bermuda", "prefix" => "+1"];
$countries[] = ["code" => "BT", "name" => "Bhutan", "prefix" => "+975"];
$countries[] = ["code" => "BO", "name" => "Bolivia", "prefix" => "+591"];
$countries[] = ["code" => "BA", "name" => "Bosnia and Herzegovina", "prefix" => "+387"];
$countries[] = ["code" => "BW", "name" => "Botswana", "prefix" => "+267"];
$countries[] = ["code" => "BR", "name" => "Brazil", "prefix" => "+55"];
$countries[] = ["code" => "IO", "name" => "British Indian Ocean Territory", "prefix" => "+246"];
$countries[] = ["code" => "VG", "name" => "British Virgin Islands", "prefix" => "+1"];
$countries[] = ["code" => "BN", "name" => "Brunei", "prefix" => "+673"];
$countries[] = ["code" => "BG", "name" => "Bulgaria", "prefix" => "+359"];
$countries[] = ["code" => "BF", "name" => "Burkina Faso", "prefix" => "+226"];
$countries[] = ["code" => "MM", "name" => "Burma Myanmar", "prefix" => "+95"];
$countries[] = ["code" => "BI", "name" => "Burundi", "prefix" => "+257"];
$countries[] = ["code" => "KH", "name" => "Cambodia", "prefix" => "+855"];
$countries[] = ["code" => "CM", "name" => "Cameroon", "prefix" => "+237"];
$countries[] = ["code" => "CA", "name" => "Canada", "prefix" => "+1"];
$countries[] = ["code" => "CV", "name" => "Cape Verde", "prefix" => "+238"];
$countries[] = ["code" => "KY", "name" => "Cayman Islands", "prefix" => "+1"];
$countries[] = ["code" => "CF", "name" => "Central African Republic", "prefix" => "+236"];
$countries[] = ["code" => "TD", "name" => "Chad", "prefix" => "+235"];
$countries[] = ["code" => "CL", "name" => "Chile", "prefix" => "+56"];
$countries[] = ["code" => "CN", "name" => "China", "prefix" => "+86"];
$countries[] = ["code" => "CO", "name" => "Colombia", "prefix" => "+57"];
$countries[] = ["code" => "KM", "name" => "Comoros", "prefix" => "+269"];
$countries[] = ["code" => "CK", "name" => "Cook Islands", "prefix" => "+682"];
$countries[] = ["code" => "CR", "name" => "Costa Rica", "prefix" => "+506"];
$countries[] = ["code" => "CI", "name" => "Côte d'Ivoire", "prefix" => "+225"];
$countries[] = ["code" => "HR", "name" => "Croatia", "prefix" => "+385"];
$countries[] = ["code" => "CU", "name" => "Cuba", "prefix" => "+53"];
$countries[] = ["code" => "CY", "name" => "Cyprus", "prefix" => "+357"];
$countries[] = ["code" => "CZ", "name" => "Czech Republic", "prefix" => "+420"];
$countries[] = ["code" => "CD", "name" => "Democratic Republic of Congo", "prefix" => "+243"];
$countries[] = ["code" => "DK", "name" => "Denmark", "prefix" => "+45"];
$countries[] = ["code" => "DJ", "name" => "Djibouti", "prefix" => "+253"];
$countries[] = ["code" => "DM", "name" => "Dominica", "prefix" => "+1"];
$countries[] = ["code" => "DO", "name" => "Dominican Republic", "prefix" => "+1"];
$countries[] = ["code" => "EC", "name" => "Ecuador", "prefix" => "+593"];
$countries[] = ["code" => "EG", "name" => "Egypt", "prefix" => "+20"];
$countries[] = ["code" => "SV", "name" => "El Salvador", "prefix" => "+503"];
$countries[] = ["code" => "GQ", "name" => "Equatorial Guinea", "prefix" => "+240"];
$countries[] = ["code" => "ER", "name" => "Eritrea", "prefix" => "+291"];
$countries[] = ["code" => "EE", "name" => "Estonia", "prefix" => "+372"];
$countries[] = ["code" => "ET", "name" => "Ethiopia", "prefix" => "+251"];
$countries[] = ["code" => "FK", "name" => "Falkland Islands", "prefix" => "+500"];
$countries[] = ["code" => "FO", "name" => "Faroe Islands", "prefix" => "+298"];
$countries[] = ["code" => "FM", "name" => "Federated States of Micronesia", "prefix" => "+691"];
$countries[] = ["code" => "FJ", "name" => "Fiji", "prefix" => "+679"];
$countries[] = ["code" => "FI", "name" => "Finland", "prefix" => "+358"];
$countries[] = ["code" => "FR", "name" => "France", "prefix" => "+33"];
$countries[] = ["code" => "GF", "name" => "French Guiana", "prefix" => "+594"];
$countries[] = ["code" => "PF", "name" => "French Polynesia", "prefix" => "+689"];
$countries[] = ["code" => "GA", "name" => "Gabon", "prefix" => "+241"];
$countries[] = ["code" => "GE", "name" => "Georgia", "prefix" => "+995"];
$countries[] = ["code" => "DE", "name" => "Germany", "prefix" => "+49"];
$countries[] = ["code" => "GH", "name" => "Ghana", "prefix" => "+233"];
$countries[] = ["code" => "GI", "name" => "Gibraltar", "prefix" => "+350"];
$countries[] = ["code" => "GR", "name" => "Greece", "prefix" => "+30"];
$countries[] = ["code" => "GL", "name" => "Greenland", "prefix" => "+299"];
$countries[] = ["code" => "GD", "name" => "Grenada", "prefix" => "+1"];
$countries[] = ["code" => "GP", "name" => "Guadeloupe", "prefix" => "+590"];
$countries[] = ["code" => "GU", "name" => "Guam", "prefix" => "+1"];
$countries[] = ["code" => "GT", "name" => "Guatemala", "prefix" => "+502"];
$countries[] = ["code" => "GN", "name" => "Guinea", "prefix" => "+224"];
$countries[] = ["code" => "GW", "name" => "Guinea-Bissau", "prefix" => "+245"];
$countries[] = ["code" => "GY", "name" => "Guyana", "prefix" => "+592"];
$countries[] = ["code" => "HT", "name" => "Haiti", "prefix" => "+509"];
$countries[] = ["code" => "HN", "name" => "Honduras", "prefix" => "+504"];
$countries[] = ["code" => "HK", "name" => "Hong Kong", "prefix" => "+852"];
$countries[] = ["code" => "HU", "name" => "Hungary", "prefix" => "+36"];
$countries[] = ["code" => "IS", "name" => "Iceland", "prefix" => "+354"];
$countries[] = ["code" => "IN", "name" => "India", "prefix" => "+91"];
$countries[] = ["code" => "ID", "name" => "Indonesia", "prefix" => "+62"];
$countries[] = ["code" => "IR", "name" => "Iran", "prefix" => "+98"];
$countries[] = ["code" => "IQ", "name" => "Iraq", "prefix" => "+964"];
$countries[] = ["code" => "IE", "name" => "Ireland", "prefix" => "+353"];
$countries[] = ["code" => "IL", "name" => "Israel", "prefix" => "+972"];
$countries[] = ["code" => "IT", "name" => "Italy", "prefix" => "+39"];
$countries[] = ["code" => "JM", "name" => "Jamaica", "prefix" => "+1"];
$countries[] = ["code" => "JP", "name" => "Japan", "prefix" => "+81"];
$countries[] = ["code" => "JO", "name" => "Jordan", "prefix" => "+962"];
$countries[] = ["code" => "KZ", "name" => "Kazakhstan", "prefix" => "+7"];
$countries[] = ["code" => "KE", "name" => "Kenya", "prefix" => "+254"];
$countries[] = ["code" => "KI", "name" => "Kiribati", "prefix" => "+686"];
$countries[] = ["code" => "XK", "name" => "Kosovo", "prefix" => "+381"];
$countries[] = ["code" => "KW", "name" => "Kuwait", "prefix" => "+965"];
$countries[] = ["code" => "KG", "name" => "Kyrgyzstan", "prefix" => "+996"];
$countries[] = ["code" => "LA", "name" => "Laos", "prefix" => "+856"];
$countries[] = ["code" => "LV", "name" => "Latvia", "prefix" => "+371"];
$countries[] = ["code" => "LB", "name" => "Lebanon", "prefix" => "+961"];
$countries[] = ["code" => "LS", "name" => "Lesotho", "prefix" => "+266"];
$countries[] = ["code" => "LR", "name" => "Liberia", "prefix" => "+231"];
$countries[] = ["code" => "LY", "name" => "Libya", "prefix" => "+218"];
$countries[] = ["code" => "LI", "name" => "Liechtenstein", "prefix" => "+423"];
$countries[] = ["code" => "LT", "name" => "Lithuania", "prefix" => "+370"];
$countries[] = ["code" => "LU", "name" => "Luxembourg", "prefix" => "+352"];
$countries[] = ["code" => "MO", "name" => "Macau", "prefix" => "+853"];
$countries[] = ["code" => "MK", "name" => "Macedonia", "prefix" => "+389"];
$countries[] = ["code" => "MG", "name" => "Madagascar", "prefix" => "+261"];
$countries[] = ["code" => "MW", "name" => "Malawi", "prefix" => "+265"];
$countries[] = ["code" => "MY", "name" => "Malaysia", "prefix" => "+60"];
$countries[] = ["code" => "MV", "name" => "Maldives", "prefix" => "+960"];
$countries[] = ["code" => "ML", "name" => "Mali", "prefix" => "+223"];
$countries[] = ["code" => "MT", "name" => "Malta", "prefix" => "+356"];
$countries[] = ["code" => "MH", "name" => "Marshall Islands", "prefix" => "+692"];
$countries[] = ["code" => "MQ", "name" => "Martinique", "prefix" => "+596"];
$countries[] = ["code" => "MR", "name" => "Mauritania", "prefix" => "+222"];
$countries[] = ["code" => "MU", "name" => "Mauritius", "prefix" => "+230"];
$countries[] = ["code" => "YT", "name" => "Mayotte", "prefix" => "+262"];
$countries[] = ["code" => "MX", "name" => "Mexico", "prefix" => "+52"];
$countries[] = ["code" => "MD", "name" => "Moldova", "prefix" => "+373"];
$countries[] = ["code" => "MC", "name" => "Monaco", "prefix" => "+377"];
$countries[] = ["code" => "MN", "name" => "Mongolia", "prefix" => "+976"];
$countries[] = ["code" => "ME", "name" => "Montenegro", "prefix" => "+382"];
$countries[] = ["code" => "MS", "name" => "Montserrat", "prefix" => "+1"];
$countries[] = ["code" => "MA", "name" => "Morocco", "prefix" => "+212"];
$countries[] = ["code" => "MZ", "name" => "Mozambique", "prefix" => "+258"];
$countries[] = ["code" => "NA", "name" => "Namibia", "prefix" => "+264"];
$countries[] = ["code" => "NR", "name" => "Nauru", "prefix" => "+674"];
$countries[] = ["code" => "NP", "name" => "Nepal", "prefix" => "+977"];
$countries[] = ["code" => "NL", "name" => "Netherlands", "prefix" => "+31"];
$countries[] = ["code" => "AN", "name" => "Netherlands Antilles", "prefix" => "+599"];
$countries[] = ["code" => "NC", "name" => "New Caledonia", "prefix" => "+687"];
$countries[] = ["code" => "NZ", "name" => "New Zealand", "prefix" => "+64"];
$countries[] = ["code" => "NI", "name" => "Nicaragua", "prefix" => "+505"];
$countries[] = ["code" => "NE", "name" => "Niger", "prefix" => "+227"];
$countries[] = ["code" => "NG", "name" => "Nigeria", "prefix" => "+234"];
$countries[] = ["code" => "NU", "name" => "Niue", "prefix" => "+683"];
$countries[] = ["code" => "NF", "name" => "Norfolk Island", "prefix" => "+672"];
$countries[] = ["code" => "KP", "name" => "North Korea", "prefix" => "+850"];
$countries[] = ["code" => "MP", "name" => "Northern Mariana Islands", "prefix" => "+1"];
$countries[] = ["code" => "NO", "name" => "Norway", "prefix" => "+47"];
$countries[] = ["code" => "OM", "name" => "Oman", "prefix" => "+968"];
$countries[] = ["code" => "PK", "name" => "Pakistan", "prefix" => "+92"];
$countries[] = ["code" => "PW", "name" => "Palau", "prefix" => "+680"];
$countries[] = ["code" => "PS", "name" => "Palestine", "prefix" => "+970"];
$countries[] = ["code" => "PA", "name" => "Panama", "prefix" => "+507"];
$countries[] = ["code" => "PG", "name" => "Papua New Guinea", "prefix" => "+675"];
$countries[] = ["code" => "PY", "name" => "Paraguay", "prefix" => "+595"];
$countries[] = ["code" => "PE", "name" => "Peru", "prefix" => "+51"];
$countries[] = ["code" => "PH", "name" => "Philippines", "prefix" => "+63"];
$countries[] = ["code" => "PL", "name" => "Poland", "prefix" => "+48"];
$countries[] = ["code" => "PT", "name" => "Portugal", "prefix" => "+351"];
$countries[] = ["code" => "PR", "name" => "Puerto Rico", "prefix" => "+1"];
$countries[] = ["code" => "QA", "name" => "Qatar", "prefix" => "+974"];
$countries[] = ["code" => "CG", "name" => "Republic of the Congo", "prefix" => "+242"];
$countries[] = ["code" => "RE", "name" => "Réunion", "prefix" => "+262"];
$countries[] = ["code" => "RO", "name" => "Romania", "prefix" => "+40"];
$countries[] = ["code" => "RU", "name" => "Russia", "prefix" => "+7"];
$countries[] = ["code" => "RW", "name" => "Rwanda", "prefix" => "+250"];
$countries[] = ["code" => "BL", "name" => "Saint Barthélemy", "prefix" => "+590"];
$countries[] = ["code" => "SH", "name" => "Saint Helena", "prefix" => "+290"];
$countries[] = ["code" => "KN", "name" => "Saint Kitts and Nevis", "prefix" => "+1"];
$countries[] = ["code" => "MF", "name" => "Saint Martin", "prefix" => "+590"];
$countries[] = ["code" => "PM", "name" => "Saint Pierre and Miquelon", "prefix" => "+508"];
$countries[] = ["code" => "VC", "name" => "Saint Vincent and the Grenadines", "prefix" => "+1"];
$countries[] = ["code" => "WS", "name" => "Samoa", "prefix" => "+685"];
$countries[] = ["code" => "SM", "name" => "San Marino", "prefix" => "+378"];
$countries[] = ["code" => "ST", "name" => "São Tomé and Príncipe", "prefix" => "+239"];
$countries[] = ["code" => "SA", "name" => "Saudi Arabia", "prefix" => "+966"];
$countries[] = ["code" => "SN", "name" => "Senegal", "prefix" => "+221"];
$countries[] = ["code" => "RS", "name" => "Serbia", "prefix" => "+381"];
$countries[] = ["code" => "SC", "name" => "Seychelles", "prefix" => "+248"];
$countries[] = ["code" => "SL", "name" => "Sierra Leone", "prefix" => "+232"];
$countries[] = ["code" => "SG", "name" => "Singapore", "prefix" => "+65"];
$countries[] = ["code" => "SK", "name" => "Slovakia", "prefix" => "+421"];
$countries[] = ["code" => "SI", "name" => "Slovenia", "prefix" => "+386"];
$countries[] = ["code" => "SB", "name" => "Solomon Islands", "prefix" => "+677"];
$countries[] = ["code" => "SO", "name" => "Somalia", "prefix" => "+252"];
$countries[] = ["code" => "ZA", "name" => "South Africa", "prefix" => "+27"];
$countries[] = ["code" => "KR", "name" => "South Korea", "prefix" => "+82"];
$countries[] = ["code" => "ES", "name" => "Spain", "prefix" => "+34"];
$countries[] = ["code" => "LK", "name" => "Sri Lanka", "prefix" => "+94"];
$countries[] = ["code" => "LC", "name" => "St. Lucia", "prefix" => "+1"];
$countries[] = ["code" => "SD", "name" => "Sudan", "prefix" => "+249"];
$countries[] = ["code" => "SR", "name" => "Suriname", "prefix" => "+597"];
$countries[] = ["code" => "SZ", "name" => "Swaziland", "prefix" => "+268"];
$countries[] = ["code" => "SE", "name" => "Sweden", "prefix" => "+46"];
$countries[] = ["code" => "CH", "name" => "Switzerland", "prefix" => "+41"];
$countries[] = ["code" => "SY", "name" => "Syria", "prefix" => "+963"];
$countries[] = ["code" => "TW", "name" => "Taiwan", "prefix" => "+886"];
$countries[] = ["code" => "TJ", "name" => "Tajikistan", "prefix" => "+992"];
$countries[] = ["code" => "TZ", "name" => "Tanzania", "prefix" => "+255"];
$countries[] = ["code" => "TH", "name" => "Thailand", "prefix" => "+66"];
$countries[] = ["code" => "BS", "name" => "The Bahamas", "prefix" => "+1"];
$countries[] = ["code" => "GM", "name" => "The Gambia", "prefix" => "+220"];
$countries[] = ["code" => "TL", "name" => "Timor-Leste", "prefix" => "+670"];
$countries[] = ["code" => "TG", "name" => "Togo", "prefix" => "+228"];
$countries[] = ["code" => "TK", "name" => "Tokelau", "prefix" => "+690"];
$countries[] = ["code" => "TO", "name" => "Tonga", "prefix" => "+676"];
$countries[] = ["code" => "TT", "name" => "Trinidad and Tobago", "prefix" => "+1"];
$countries[] = ["code" => "TN", "name" => "Tunisia", "prefix" => "+216"];
$countries[] = ["code" => "TR", "name" => "Turkey", "prefix" => "+90"];
$countries[] = ["code" => "TM", "name" => "Turkmenistan", "prefix" => "+993"];
$countries[] = ["code" => "TC", "name" => "Turks and Caicos Islands", "prefix" => "+1"];
$countries[] = ["code" => "TV", "name" => "Tuvalu", "prefix" => "+688"];
$countries[] = ["code" => "UG", "name" => "Uganda", "prefix" => "+256"];
$countries[] = ["code" => "UA", "name" => "Ukraine", "prefix" => "+380"];
$countries[] = ["code" => "AE", "name" => "United Arab Emirates", "prefix" => "+971"];
$countries[] = ["code" => "GB", "name" => "United Kingdom", "prefix" => "+44"];
$countries[] = ["code" => "US", "name" => "United States", "prefix" => "+1"];
$countries[] = ["code" => "UY", "name" => "Uruguay", "prefix" => "+598"];
$countries[] = ["code" => "VI", "name" => "US Virgin Islands", "prefix" => "+1"];
$countries[] = ["code" => "UZ", "name" => "Uzbekistan", "prefix" => "+998"];
$countries[] = ["code" => "VU", "name" => "Vanuatu", "prefix" => "+678"];
$countries[] = ["code" => "VA", "name" => "Vatican City", "prefix" => "+39"];
$countries[] = ["code" => "VE", "name" => "Venezuela", "prefix" => "+58"];
$countries[] = ["code" => "VN", "name" => "Vietnam", "prefix" => "+84"];
$countries[] = ["code" => "WF", "name" => "Wallis and Futuna", "prefix" => "+681"];
$countries[] = ["code" => "YE", "name" => "Yemen", "prefix" => "+967"];
$countries[] = ["code" => "ZM", "name" => "Zambia", "prefix" => "+260"];
$countries[] = ["code" => "ZW", "name" => "Zimbabwe", "prefix" => "+263"];
