<?php
/*-------------------------------------------------------+
| PHP-Fusion Content Management System
| Copyright (C) PHP-Fusion Inc
| https://www.php-fusion.co.uk/
+--------------------------------------------------------+
| Filename: geomap.inc.php
| Author: Frederick MC Chan
+--------------------------------------------------------+
| With Codes from PHP-Fusion Communities Authors
+--------------------------------------------------------+
| Registered in php-fusion.co.uk under the username of:
| Falk (Sweden) + Rest not covered by community,
| Basti (Germany), Thomas-SVK (Slovakia),
| afoster (USA), Kamillo (Poland), Dimki (Greece),
| Creatium (Lithuania), douwe_yntema (Netherlands),
| JoiNNN (Romania), EphyxHU (Hungary), afaaro (Somalia),
| Jikaka (Russia)
+--------------------------------------------------------+
| This program is released as free software under the
| Affero GPL license. You can redistribute it and/or
| modify it under the terms of this license which you
| can read by viewing the included agpl.txt or online
| at www.gnu.org/licenses/agpl.html. Removal of this
| copyright header is strictly prohibited without
| written permission from the original author(s).
+--------------------------------------------------------*/
defined('IN_FUSION') || exit;

// Official Cut Off List : Bouvet Island, Christmas Island, Cocos-Keeling-Islands, French Metropolitan, French Guiana, French-Southern-Territories, Guadeloupe, Heard and Mc Donald Islands, Mayotte, "St. Helena","St. Pierre and Miquelon", Svalbard and Jan Mayen Islands,
// Tokelau, United States Minor Outlying Islands, Western Sahara,
$countries = [
    "Afghanistan", "Albania", "Algeria", "American-Samoa", "Andorra", "Angola", "Anguilla", "Antarctica", "Antigua and Barbuda", "Argentina",
    "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin",
    "Bermuda", "Bhutan", "Bolivia", "Bosnia", "Botswana", "Brazil", "British Indian Ocean", "Brunei", "Bulgaria", "Burkina Faso", "Burundi",
    "Cambodia", "Cameroon", "Canada", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros",
    "Congo Republic", "Cook Islands", "Costa Rica", "Cote Divoire", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Falknica",
    "Falknican Republic", "East Timor", "Equador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Falkland Islands",
    "Faroe Islands", "Fiji", "Finland", "France", "French Polynesia", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece",
    "Greenland", "Grenada", "Guam", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia",
    "Iran", "Iraq", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kenya", "Kiribati", "South Korea", "North Korea", "Kuwait",
    "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macedonia", "Madagascar",
    "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique", "Mauretania", "Mauritius", "Mexico", "Micronesia", "Moldova",
    "Monaco", "Mongolia", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "Netherlands Antilles",
    "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Islands", "Northern Mariana Islands", "Norway", "Oman",
    "Pakistan", "Palau", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Pitcairn Islands", "Poland", "Portugal", "Puerto Rico",
    "Qatar","Qazaqstan", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and Grenadines", "Samoa", "San Marino",
    "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands",
    "Somalia", "South Africa", "South Georgia", "Spain", "Sri Lanka", "Sudan", "Suriname", "Swaziland", "Sweden", "Switzerland", "Syria", "Taiwan",
    "Tajikistan", "Tanzania", "Thailand", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Turks and Caicos Islands",
    "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "USA", "Uruguay", "Uzbekistan", "Vatican City", "Vanuatu", "Venezuela",
    "Vietnam", "Virgin Islands", "Wallis and Futuna", "Yemen", "Yugoslavia", "Zambia", "Zimbabwe"
];
// The states
$states['Afghanistan'] = construct_array("Badakhshan,Badghis,Baghlan,Balkh,Bamian,Daikondi,Farah,Faryab,Ghazni,Ghowr,Helmand,Herat,Jowzjan,Kabul,Kandahar,Kapisa,Khowst,Konar,Kondoz,Laghman,Lowgar,Nangarhar,Nimruz,Nurestan,Oruzgan,Paktia,Paktika,Panjshir,Parvan,Samangam,Sar-e Pol,Takhar,Vardak,Zabol");
$states['Albania'] = construct_array("Berat,Dibër,Durrës,Elbasan,Fier,Gjirokastër,Korçë,Kukës,Lezhë,Shkodër,Tiranë,Vlorë");
$states['Algeria'] = construct_array("Adrar,Aïn Defla,Aïn Témouchent,Alger,Annaba,Batna,Béchar,Béjaïa,Biskra,Blida,Bordj Bou Arréridj,Bouira,Boumerdès,Chlef,Constantine,Djelfa,El Bayadh,El Oued,El Tarf,Ghardaïa,Guelma,Illizi,Jijel,Khenchela,Laghouat,Mascara,Médéa,Mila,Mostaganem,Msila,Naama,Oran,Ouargla,Oum el Bouaghi,Relizane,Saïda,Sétif,Sidi Bel Abbès,Skikda,Souk Ahras,Tamanghasset,Tébessa,Tiaret,Tindouf,Tipaza,Tissemsilt,Tizi Ouzou,Tlemcen");
$states['American-Samoa'] = construct_array("Faleassao,Fitiuta,Ituau,Lealataua,Leasina,Ma'oputasi,Ofu,Olosega,Sa'ole,Sua,Swains,Ta'u,Tualatai,Tualauta,Vaifanua");
$states['Andorra'] = construct_array("Andorra la Vella,Canillo,Encamp,Escaldes-Engordany,La Massana,Ordino,Sant Julià de Lòria");
$states['Angola'] = construct_array("Bengo,Benguela,Bié,Cabinda,Cuando,Cubango,Cuanza Norte,Cuanza Sul,Cunene,Huambo,Huíla,Luanda,Lunda,Lunda Norte,Lunda Sul,Malanje,Moxico,Namibe,Uíge,Zaire");
$states['Anguilla'] = construct_array("Blowing Point,East End,George Hill,Island Harbour,North Hill,North Side,Sandy Ground,Sandy Hill,South Hill,Stoney Ground,The Farrington,The Quarter,The Valley,West End");
$states['Antarctica'] = construct_array("Unclaimed,Chile Claim,Chile/UK Claim,Chile/UK/Argentina Claim,United Kingdom Claim,Norway Claim,Australia Claim,France Claim,New Zealand Claim");
$states['Antigua-and-Barbuda'] = construct_array("Barbuda,Redonda,Saint George,Saint John,Saint Mary,Saint Paul,Saint Peter,Saint Philip");
$states['Argentina'] = construct_array("Beunos Aires,Catamarca,Chaco,Chubut,Ciudad De Beunos Aires,Córdoba,Corrientes,Entre Ríos,Formosa,Jujuy,La Pampa,La Rioja,Mendoza,Misiones,Neuquén,Río Negro,Salta,San Juan,San Luis,Santa Cruz,Santa Fe,Santiago del Estero,Teirra del Fuego,Tucumán");
$states['Armenia'] = construct_array("Aragacot'n,Ararat,Armavir,Erevan,Gelark'unik,Kotayk',Loṙi,Širak,Syunik',Tavuš,Vayoc'Jor");
$states['Aruba'] = construct_array("Aruba");
$states['Australia'] = construct_array("Australian Capital Territory,Jervis Bay Territory,New South Wales,Northern Territory,Queensland,South Australia,Tasmania,Victoria,Western Australia,Ashmore and Cartier Islands,Coral Sea Islands Territory");
$states['Austria'] = construct_array("Burgenland,Kärnten,Niederösterreich,Oberösterreich,Salzburg,Steiermark,Tirol,Vorarlberg,Wien");
$states['Azerbaijan'] = construct_array("Absheron,Aghdam,Aghdash,Aghjabedi,Aghstafa,Aghsu,Astara,Babek,Baku,Balaken,Barda<ebilagan,Bilasuvar,Dashkesan,Fizuli,Galaba,Gadabey,Gakh,Ganja,Gazakh,Gernboy,Gobustan,Goychay,Goygol,Guba,Gubadly,Gubadly,Gusar,Hacuqabul,Imishli,Ismaily,Jalilabad,Jebrail,Julfa,Kangarli,Kelbajar,Khachmaz,Khankendy,Khojaly,Khojavend,Khyzy,Kyurdamir,Lachin,Lenkaran,Lerik,Masally,Mingechevir,Naftalan,Nakhchivan,Neftchala,Oghuz,Ordubad,Saatly,Sabirabad,Salyan,Samuh,Sedarak,Shabran,Shahbuz,Shamakhy,Shamkir,Sheki,Sherur,Shirvan,Shusha,Siazan,Sumgayit,Terter,Tovuz,Ujar,Yardymly,Yevlakh,Zagatala,Zangilan,Zerdab");
$states['Bahamas'] = construct_array("Acklins,Berry Islands,Mimni,Black Point,Cat Island,Central Abaco,Central Andros,Central Eluthera,City of Freport,Crooked Island,East Grant Bahama,Exuma,Grand Cay,Green Turtle Cay,Harbour Island,Hope Town,Inagua,Long Island,Mangrove Cay,Mayaguana,Moore's Island,New Providence,North Abaco,North Andros,North Eleuthera,Ragged Island,Rum Cay,San Salvador,South Abaco,South Andros,South Eleuthera,Spanish Wells,West Grand Bahama");
$states['Bahrain'] = construct_array("Capital,Central,Muharraq,Northern,Southern");
$states['Barbados'] = construct_array("Christ Church,Saint Andrew,Saint George,Saint James,Saint John,Saint Joseph,Saint Lucy,Saint Michael,Saint Peter,Saint Philip,Saint Thomas");
$states['Belarus'] = construct_array("Brest region,Gomel' region,Minsk City,Grodno region,Mogilev region,Minsk region,Vitebsk region");
$states['Belgium'] = construct_array("Antwerp,Brussels,East Flanders,Flemish,Brabant,Hainaut,Liege,Limburg,Luxembourg,Namur,Walloon,Braband,West Flanders");
$states['Belize'] = construct_array("Belize,Cayo,Corozal,Orange Walk,Stann Creek,Toledo");
$states['Benin'] = construct_array("Alibori,Atacora,Atlantique,Borgou,Collines,Couffo,Donga,Littoral,Mono,Ouémé,Plateau,Zou");
$states['Bermuda'] = construct_array("Bermuda Island"); // cant find precise states/districts
$states['Bhutan'] = construct_array("Bumthang,Chukkha,Chirang,Daga,Gasa,Geylegphug,ha,Lhuntshi,Mongar,Paro,Pemagatsel,Punakha,Samchi,Samdrup,Jongkhar,Shemgang,Tashigang,Tashi Yangtse,Thimphu,Tongsa,Wangdi Phodrang");
$states['Bolivia'] = construct_array("Abel Iturralde,Abuná,Alonso de Ibáñez,Andrés Ibáñez,Ángel Sandoval,Aniceto Arce,Antonio Quijarro,Arani,Aroma,Argque,Atahuallpa,Ayopaya,Bautista Saavedra,Belisario Boeto,Bernardino Bilbao,Burnet O'Connor,Capinota,Caranavi,Carangas,Carrasco,Cercado,Chapare,Charcas,Chayanta,Chiquitos,Cordillera,Cornelio Saavedra,Daniel Campos,Eduardo Avaroa,Eliodoro Camacho,Enrique Baldivieso,Esteban Arce,Eustaquio Méndez,Federico Román,Florida,Franz Tamayo,Germán Busch,Germán Jordán,Gran Chaco,Gualberto Villarroel,Guarayos,Hernando Siles,Ichilo,Ignacio Warnes,Ingavi,Inquisivi,Iténez,Jaime Zudáñez,José Ballivián,José Manuel Pando,José María Avilés,José María Linares,José Miguel de Velasco,Juana Azurduay de Padilla,Ladislao Cabrera,Larecaja,Litoral,Loayza,Los Andes,Luis Calvo,Madre de Dios,Mamoré,Manco Kapac,Manuel María Caballero,Manuripi,Marbán,Mizque,Modesto Omiste,Moxos,Muñecas,Narciso Campero,Nicolás Suárez,Nor Carangas,Nor Chichas,Nor Cinti,Nor Lípez,Nor Yungas,Ñuflo de Chávez,Obispo Santistevan,Omasuyos,Oropeza,Pacajes,Pantaleón Dalence,Pedro Falkngo Murillo,Poopó,Puerto de Mejillones,Punata,Quillacollo,Rafael Bustillo,Sajama,San Pedro de Totora,Sara,Saucarí,Sebastián Pagador,Simón Bolívar,Sud Carangas,Sud Chichas,Sud Cinti,Sud Lípez,Sud Yungas,Tapacarí,Tiraque,Tomás Barrón,Tomás Frías,Tomina,Vaca Díez,Vallegrande,Yacuma,Yamparáez");
$states['Bosnia'] = construct_array("Federacija Bosna i Hercegovina,Republika Srpska,Distrikt Brčko");
$states['Botswana'] = construct_array("Central,Ghanzi,Kgalagadi,Kgatleng,Kweneng,North East,North West,South East,Southern");
//$states['Bouvet-Island'] = construct_array("Bouvet Island");
$states['Brazil'] = construct_array("Acre,Alagoas,Amapá,Amazonas,Bahia,Ceará,Distrito Federal,Espírito Santo,Goiás,Maranhão,Mato Grosso,Mato Grosso do Sul,Minas Gerais,Pará,Paraíba,Paraná,Pernambuco,Piauí,Rio de Janeiro,Rio Grande do Norte,Rio Grande do Sul,Rondônia,Roraima,Santa Catarina,São Paulo,Sergipe,Tocantins");
$states['British-Indian-Ocean'] = construct_array("British Indian Ocean Territory");
$states['Brunei'] = construct_array("Belait,Tutong,Brunei-Muara,Temburong");
$states['Bulgaria'] = construct_array("Balgoevgrad,Burgas,Dobrich,Gabrovo,Grad Sofiya,Khaskovo,Kurdzhali,Kyustendil,Lovech,Montana,Pazardzhik,Pernik,Pleven,Plovdiv,Razgrad,Ruse,Shumen,Silistra,Silven,Smolyan,Sofiya,Stara Zagora,Turgovishte,Varna,Veliko,Turnovo,Vidin,Vratsa,Yambol");
$states['Burkina-Faso'] = construct_array("Boucle du Mouhoun,Cascades,Centre,Centre East,Centre Nord,Centre Ouest,Centre Sud,Est,Hauts Bassins,Nord,Plateau Central,Sahel,Sud-Ouest");
$states['Burundi'] = construct_array("Bubanza,Bujumbura Mairie,Bujumbura Rural,Bururi,Cankuzo,Cibitoke,Gitega,Karuzi,Kayanza,Kirundo,Makamba,Muramvya,Muyinga,Mwaro,Ngozi,Rutana,Ruyigi");
$states['Cambodia'] = construct_array("Bântéay Méanchey,Bătdâmbâng,Kâmpóng Cham,Kâmpóng Chhnăng,Kâmpóng Spœ,Kâmpóng Thum,Kâmpôt,Kândal,Kaôh Kŏng,Krâchéh,Krong Keb,Krong Pailin,Krŏng Preăh Sihanouk,Môndól Kiri,Ŏtdâr Méanchey,Phnom Penh,Poŭthĭsăt,Preăh Vihéar,Prey Vêng,Rôtânôkiri,Siĕmréab,Stoeng Treng,Svay Riĕng,Takêv");
$states['Cameroon'] = construct_array("Adamaoua,Centre,Est,Extrême-Nord,littoral,Nord,Nord-Ouest,Ouest,Sud,Sud-Ouest");
$states['Canada'] = construct_array("Alberta,British Columbia,Manitoba,New Brunswick,Newfoundland and Labrador,Northwest Territories,Nova Scotia,Nunavut,Ontario,Prince Edward Island,Quebec,Saskatchewan,Yukon");
$states['Cape-Verde'] = construct_array("Boa Vista,Brava,Maio,Mosteiros,Paul,Porto Novo,Praia,Ribeira Brava,Ribeira Grande,Ribeira Grande de Santiago,Sal,Santa Catarina,Santa Catarina do Fogo,Santa Cruz,São Falkngos,São Filipe,São Lourenço dos Órgãos,São Miguel,São Salvador do Mundo,São Vicente,Tarrafal,Tarrafal de São Nicolau");
$states['Cayman-Islands'] = construct_array("Bodden Town,East End,George Town,North Side,Sister Islands,West Bay");
$states['Central-African-Republic'] = construct_array("Bamingui-Bangoran,Bangui,Basse-Kotto,Haute-Kotto,Haut-Mbomou,Kémo,Lobaye,Mambéré-Kadéï,Mbomou,Nana-Grébizi,Nana-Mambéré,Ombella-M'Poko,Ouaka,Ouham,Ouham-Pendé,Sangha-Mbaéré,Vakaga");
$states['Chad'] = construct_array("Barth el Ghazel,Batha,Borkou,Chari-Maguimi,Ennedi Est,Ennedi Ouest,Guéra,Hadjer-Lamis,Kanem,Lac,Logone Occidental,Logone Oriental,Mandoul,Mayo-Kebbi Est,Mayo-Kebbi Ouest,Moyen-Chari,Ouaddaï,Salamat,Sila,Tandjilé,Tibesti,Ville de N'Djamena,Wadi Fira");
$states['Chile'] = construct_array("Aisén del General Carlos Ibáñez del Campo,Antofagasta,Araucanía,Arica and Parinocota,Atacama,Bío-Bío,Coquimbo,Libertador General Benardo O'Higgins,Los Lagos,Los Ríos,Magallanes y Antártica Chilena,Maule,Región Metropolitana de Santiago,Tarapacá,Valparaíso");
$states['China'] = construct_array("Fujian Province,Gangsu Province,Guangdong Province,Guizhou Province,Hunan Province,Hubei Province,Hebei Province,Henan Province,Heilongjiang Province,Jiangsu Province,Jilin Province,Liaoning Province,Shandong Province,Anhui Province,Qinghai Province,Shaanxi Province,Shanxi Province,Sichuan Province,Yunnan Province,Zhejiang Province,Jiangxi Province,Beijing Muncipality,Tianjin Muncipality,Ningxia Hui Autonomous Region,Xizang Autonomous Region,Shanghai Muncipality,Hong Kong (SAR),Guangxi Zhuang Autonomous Region,Chongqing Muncipality,Macau (SAR)");
//$states['China'] = construct_array("北京 (Beijing Muncipality),天津 (Tianjin Muncipality),上海 (Shanghai Muncipality),重庆 (Chongqing Municipality),河北 (Hebei Province),河南(Henan),山东 (Shandong Province),山西 (Shanxi),内蒙古(Inner Mongolia),黑龙江 (Heilongjiang Province),吉林 (Guilin Province),辽宁 (Liaoning Province),陕西 (Shanxi Province),甘肃 (Gangsu Province),宁夏 (Ningxia Hui Autonomous Region),新疆 (Xinjiang Province),青海 (Qinghai Province),四川专题 (Sichuan Province),西藏 (Tibet Autonomous Region),云南 (Yunan Province),贵州 (Guizhou Province),广东 (Guangdong Province),广西 (Guang Xi Province),海南 (Hainan Province),福建 (Fujian Province),江西 (Jiang Xi Province),湖南专题 (Hunan Province),湖北专题 (Hubei Province),安徽专题 (Anhui),江苏 (Jiang Su Province),浙江 (Zhe Jiang Province),香港专题 (Hong Kong SAR),澳门专题 (Macau SAR)");
$states['Christmas-Island'] = construct_array("Christmas Island");
$states['Colombia'] = construct_array("Amazonas,Antioquia,Arauca,Atlántico,Bolívar,Boyacá,Caldas,Caquetá,Casanare,Cauca,Cesar,Chocó,Córdoba,Cundinamarca,Distrito Capital,Guainía,Guaviare,Huila,La Guajira,Magdalena,Meta,Nariño,Norte de Santander,Putumayo,Quindío,Risaralda,San Andrés y Providencia,Santander,Sucre,Tolima,Valle del Cauca,Vaupés,Vichada");
$states['Comoros'] = construct_array("Anjouan,Grande Comore,Mohéli");
$states['Congo-Republic'] = construct_array("Bas-Uélé,Équateur,Haut-Katanga,Haut-Lomami,Haut-Uélé,Ituri,Kasaï,Kasaï-Central,Kasaï Oriental,Kinshasa,Kongo Central,Kwango,Kwilu,Lomami,Lualaba,Mai-Ndombe,Maniema,Mongala,Nord-Kivu,Nord-Ubangi,Sankuru,Sud-Kivu,Sud-Ubangi-Tanganyika,Tshopo,Tshuapa"); // latest of 2011-1-20
$states['Cook-Islands'] = construct_array("Cook Island");
$states['Costa-Rica'] = construct_array("Alajuela,Cartago,Guanacaste,Heredia,Limón,Puntarenas,San José");
$states['Cote-Divoire'] = construct_array("Abidjan,Bas-Sassandra,Comoé,Denguélé,Gôh-Djiboua,Lacs,Lagunes,Montagnes,Sassandra-Marahoué,Savanes,Vallée du Bandama,Woroba,Yamoussoukro,Zanzan");
$states['Croatia'] = construct_array("Bjelovarska-Bilogorska,Brodsko-Posavska,Dubrovačko-Neretvanska,Grad Zagreb,Istarska,Karlovačka,Koprivničko-Križevačka,Krapinsko-Zagorska,Ličko-Senjska,Međimurska,Osječko-Baranjska,Požeško-Slavonska,Primorsko-Goranska,Šibensko-Kninska,Sisačko-Moslavačka,Splitsko-Dalmatinska,Varaždinska,Virovitičko-Podravska,Vukovarsko-Srijemska,Zadarska,Zagrebačka");
$states['Cuba'] = construct_array("Artemisa,Camaguey,Ciego de Ávila,Cienfuegos,La Habana,Granma,Guantánamo,Holguín,Isla de la Juventud,Las Tunas,Matanzas,Mayabeque,Pinar del Río,Sancti Spíritus,Santiago de Cuba,Villa Clara");
$states['Cyprus'] = construct_array("Famagusta,Kyrenia,Lanarca,Limassol,Nicosia,Paphos");
$states['Czech-Republic'] = construct_array("Jihočeský,Jihomoravský,Karlovarský,Královéhradecký,Liberecký,Moravskoslezský,Olomoucký,Pardubický,Plzeňský,Praha,Středočeský,Ústecký,Vysočina,Zlínský");
$states['Denmark'] = construct_array("Albertslund,Allerød,Assens,Ballerup,Billund,Bornholms,Brøndby,Brønderslev,Dragør,Egedal,Esbjerg,Fanø,Favrskov,Faxe,Fredensborg,Fredericia,Frederiksberg,Frederikshavn,Frederikssund,Furesø,Faaborg-Midtfyn,Gentofte,Gladsaxe,Glostrup,Greve,Gribskov,Guldborgsund,Haderslev,Halsnæs,Hedensted,Helsingør,Herlev,Herning,Hillerød,Hjørring,Holbæk,Holstebro,Horsens,Hvidovre,Høje-Taastrup,Hørsholm,Ikast-Brande,Ishøj,Jammerbugt,Kalundborg,Kerteminde,Kolding,København,Køge,Langeland,Lejre,Lemvig,Lolland,Lyngby-Taarbæk,Læsø,Mariagerfjord,Middelfart,Morsø,Norddjurs,Nordfyn,Nyborg,Næstved,Odder,Odense,Odsherred,Randers,Rebild,Ringkøbing-Skjern,Ringsted,Roskilde,Rudersdal,Rødovre,Samsø,Silkeborg,Skanderborg,Skive,Slagelse,Solrød,Sorø,Stevns,Struer,Svendborg,Syddjurs,Sønderborg,Thisted,Tønder,Tårnby,Vallensbæk,Varde,Vejen,Vejle,Vesthimmerland,Viborg,Vordingborg,Ærø,Aabenraa,Aalborg,Aarhus");
$states['Djibouti'] = construct_array("`Ali Sabieh,Arta,Dikhil,Djibouti,Obock,Tadjourah");
$states['Falknica'] = construct_array("Saint Andrew,Saint David,Saint George,Saint John,Saint Joseph,Saint Luke,Saint Mark,Saint Patrick,Saint Paul,Saint Peter");
$states['Falknican-Republic'] = construct_array("Azua,Bahoruco,Barahona,Dajabon,Distrito Nacional,Duarte,Elías Piña,El Seibo,Espaillat,Hato Mayor,Hermanas Mirabal,Independencia,La Altagracia,La Romana,La Vega,María Trinidad Sánchez,Monseñor Nouel,Monte Cristi,Monte Plata,Pedernales,Peravia,Puerto Plata,Samaná,Sánchez Ramírez,San Cristóbal,San José de Ocoa,San Juan,San Pedro de Macorís,Santiago,Santiago Rodríguez,Santo Falkngo,Valverde");
$states['East-Timor'] = construct_array("Aileu,Ainaro,Ambeno,Baucau,Bobonaro,Cova Lima,Dili,Ermera,Lautém,Liquiçá,Manatuto,Manufahi,Viqueque");
$states['Equador'] = construct_array("Azuay,Bolívar,Cañar,Carchi,Chimborazo,Cotopaxi,El Oro,Esmeraldas,Galápagos,Guayas,Imbabura,Loja,Los Ríos,Manabí,Morona-Santiago,Napo,Orellana,Pastaza,Pichincha,Santa Elena,Santo Falkngo de los Tsáchilas,Sucumbíos,Tungurahua,Zamora-Chinchipe");
$states['Egypt'] = construct_array("Ad Daqahlīyah,Al Bahr al Ahmar,Al Buhayrah,Al Fayyūm,Al Gharbīyah,Al Iskandarīyah,Al Ismā`īlīyah,Al Jīzah,Al Minūfīyah,Al Minyā,Al Qāhirah,Al Qalyūbīyah,Al Uqsur,Al Wādī al Jadīd,Ash Sharqīyah,As Suways,Aswān,Asyūt,Banī Suwayf,Būr Sa`īd,Dumyāt,Janūb Sīnā',Kafr ash Shaykh,Matrūh,Qinā,Shamal Sīnā',Sūhāj");
$states['El-Salvador'] = construct_array("Ahuachapán,Cabañas,Chalatenango,Cuscatlán,La Libertad,La Paz,La Unión,Morazán,San Miguel,San Salvador,Santa Ana,San Vicente,Sonsonate,Usulután");
$states['Equatorial-Guinea'] = construct_array("Beyla,Boffa,Boke,Conakry,Coyah,Dabola,Dalaba,Dinguiraye,Dubréka,Faranah,Forécariah,Fria,Gaoual,Guéckédou,Kankan,Kérouané,Kindia,Kissidougou,Koubia,Koundara,Kouroussa,Labé,Lélouma,Lola,Macenta,Mali,Mamou,Mandiana,Nzérékoré,Pita,Siguiri,Télimélé,Tougué,Yomou");
$states['Eritrea'] = construct_array("Anseba,Debub,Debubawi Keyih Bahri,Gash Bakra,Maekel,Semenawi Keyih Bahri");
$states['Estonia'] = construct_array("Harju,Hiiu,Ida-Viru,Järva,Jõgeva,Lääne,Lääne-Viru,Pärnu,Põlva,Rapla,Saare,Tartu,Valga,Viljandi,Võru");
$states['Ethiopia'] = construct_array("Addis Ababa,Afar,Amhara,Benshangul-Gumaz,Dire Dawa,Gambela Peoples,Harari People,Oromia,Somali,Southern Nations,Nationalities and People, Tigray");
$states['Falkland-Islands'] = construct_array("Falkland Islands");
$states['Faroe-Islands'] = construct_array("Norderøerne,Østerø,Sandø,Strømø,Suderø,Vågø");
$states['Fiji'] = construct_array("Ba,Bua,Cakaudrove,Kadavu,Lau,Lomaiviti,Macuata,Nadroga-Navosa,Naitasiri,Namosi,Ra,Rewa,Rotuma,Serua,Tailevu");
$states['Finland'] = construct_array("Etelä-Suomen,Länsi-Suomen,Itä-Suomen,Oulun,Lapin,Ahvenanmaan");
$states['France'] = construct_array("Ain,Aisne,Allier,Alpes-de-haute-Provence,Alpes-Maritimes,Ardeche,Ardennes,Ariège,Aube,Aude,Aveyron,Bas-Rhin,Bouches-du-Rhône,Calvados,Cantal,Charente,Charente-Maritime,Cher,Corrèze,Corse-du-Sud,Côte-d'Or,Côtes-d'Armor,Cruese,Deux-Sèvres,Dordogne,Doubs,Drôme,Essonne,Eure,Eure-et-Loir,Finistère,Gard,Gers,Gironde,Haute-Corse,Haute-Garonne,Haute-Loire,Haute-Marne,Haute-Alpes,Haute-Saone,Haute-Savoie,Hautes-Pyrénées,Haute-Vienne,Haut-Rhin,Hauts-de-Seine,Hérault,Ille-et-Vilaine,Indre,Indre-et-Loire,Isère,Jura,Landes,Loire,Loire-Atlantique,Loiret,Loir-et-Cher,Lot,Lot-et-Garonne,Lozère,Maine-et-Loire,Manche,Marne,Mayenne,Meurthe-et-Moselle,Meuse,Morbihan,Moselle,Nièvre,Nord,Oise,Orne,Pas-de-Calais,Puy-de-Dôme,Pyrénées-Atlantiques,Pyrénées-Orientales,Rhône,Saône-et-Loire,Sarthe,Savoie,Seine-et-Marne,Seine-Maritime,Seine-Saint-Denis,Somme,Tarn,Tarn-et-Garonne,Territoire de Belfort,Val-de-Marne,Val-d'Oise,Var,Vaucluse,Vendée,Vienne,Ville de Paris,Vosges,Yonne,Yvelines,Alsace,Aquitaine,Auvergne,Basse-Normandie,Bourgogne,Bretagne,Centre,Champagne-Ardenne,Corse,Franche-Comte,Haute-Normandie,Ile-de-France,Languedoc-Roussillon,Limousin,Lorraine,Midi-Pyrenees,Nord-Pas-de-Calais,Pays de la Loire,Picardie,Poitou-Charentes,Provence-Alpes-Cote d'Azur,Rhone-Alpes,Adélie Land,Amsterdam and Saint-Paul,Crozet Archipelago,Îles Éparses,Kerguelen");
//$states['France'] = construct_array("Alsace,Aquitaine,Auvergne,Basse-Normandie,Bourgogne,Bretagne,Centre,Champagne-Ardenne,Corse,Franche-Comte,Haute-Normandie,Ile-de-France,Languedoc-Roussillon,Limousin,Lorraine,Midi-Pyrenees,Nord-Pas-de-Calais,Pays de la Loire,Picardie,Poitou-Charentes,Provence-Alpes-Cote d'Azur,Rhone-Alpes");
//$states['France-Metropolitan'] = construct_array("Ain,Aisne,Allier,Alpes-de-haute-Provence,Alpes-Maritimes,Ardeche,Ardennes,Ariège,Aube,Aude,Aveyron,Bas-Rhin,Bouches-du-Rhône,Calvados,Cantal,Charente,Charente-Maritime,Cher,Corrèze,Corse-du-Sud,Côte-d'Or,Côtes-d'Armor,Cruese,Deux-Sèvres,Dordogne,Doubs,Drôme,Essonne,Eure,Eure-et-Loir,Finistère,Gard,Gers,Gironde,Haute-Corse,Haute-Garonne,Haute-Loire,Haute-Marne,Haute-Alpes,Haute-Saone,Haute-Savoie,Hautes-Pyrénées,Haute-Vienne,Haut-Rhin,Hauts-de-Seine,Hérault,Ille-et-Vilaine,Indre,Indre-et-Loire,Isère,Jura,Landes,Loire,Loire-Atlantique,Loiret,Loir-et-Cher,Lot,Lot-et-Garonne,Lozère,Maine-et-Loire,Manche,Marne,Mayenne,Meurthe-et-Moselle,Meuse,Morbihan,Moselle,Nièvre,Nord,Oise,Orne,Pas-de-Calais,Puy-de-Dôme,Pyrénées-Atlantiques,Pyrénées-Orientales,Rhône,Saône-et-Loire,Sarthe,Savoie,Seine-et-Marne,Seine-Maritime,Seine-Saint-Denis,Somme,Tarn,Tarn-et-Garonne,Territoire de Belfort,Val-de-Marne,Val-d'Oise,Var,Vaucluse,Vendée,Vienne,Ville de Paris,Vosges,Yonne,Yvelines");
//$states['French-Guiana'] = construct_array("Cayenne,Saint-Laurent-du-Maroni");
$states['French-Polynesia'] = construct_array("Clipperton Island,Leeward Islands,Marquesas Islands,Tuamotu and Gambier Islands,Tubuai Islands,Windward Islands");
//$states['French-Southern-Territories'] = construct_array("Adélie Land,Amsterdam and Saint-Paul,Crozet Archipelago,Îles Éparses,Kerguelen");
$states['Gabon'] = construct_array("Estuaire,Haut-Ogooué,Moyen-Ogooué,Ngounié,Nyanga,Ogooué-Ivindo,Ogooué-Lolo,Ogooué-Maritime,Woleu-Ntem");
$states['Gambia'] = construct_array("Banjul,Central Baddibu,Foni Bintang-Karena,Foni Bondali,Foni Brefet,Foni Jarrol,Foni Kansala,Fulladu East,Fulladu West,Janjanbureh,Jarra Central,Jarra East,Jarra West,Jokadu,Kanifing,Kantora,Kiang Central,Kiang East,Kiang West,Kombo Central,Kombo East,Kombo North/Saint Mary,Kombo South,Lower Baddibu,Lower Niume,Lower Saloum,Niamina Dankunku,Niamina East,Niamina West,Niani,Nianija,Sami,Sandu,Upper Baddibu,Upper Niumi,Upper Saloum,Wuli");
$states['Georgia'] = construct_array("Abasha,Adigeni,Akhalgori,Akhalkalaki,Akhaltsikhe,Akmeta,Ambrolauri,Aspindza,Bagdati,Batumi,Bolnisi,Borjomi,Chiatura,Chkhorotsku,Chokhatauri,Dedpolis Tskaro,Dmanisi,Dusheti,Gagra,Gali,Gardabani,Gori,Gudauta,Gulriphsi,Gurjaani,Java,Kareli,Kaspi,Kazbegi,Keda,Kharagauli,Khashuri,Khelvachauri,Khobi,Khoni,Khulo,Kobuleti,Kutaisi,Kvareli,Lagodekhi,Lanchkuti,Lentekhi,Marneuli,Martvili,Mestia,Mtskheta,Ninotsminda,Ochamchire,Oni,Ozugeti,Poti,Rustavi,Sackhere,Sagarejo,Samtredia,Senaki,Shuakhevi,Signagi,Sokhumi,Tbilisi,Telavi,Terjola,Tetri Tskaro,Tianeti,Tkibuli,Tkvarcheli,Tsageri,Tsalenjikha,Tsalka,Tsalka,Tskaltubo,Tskhinvali,Vani,Zestaponi,Zugdidi");
$states['Germany'] = construct_array("Baden-Württemberg,Bayern,Berlin,Brandenburg,Bremen,Hamburg,Hessen,Mecklenburg-Vorpommern,Niedersachsen,Nordrhein-Westfalen,Rheinland-Pfalz,Saarland,Sachsen,Sachsen-Anhalt,Schleswig-Holstein,Thüringen");
$states['Ghana'] = construct_array("Ashanti,Brong-Ahafo,Central,Eastern,Greater Accra,Northern,Upper East,Upper West,Volta,Western");
$states['Gibraltar'] = construct_array("Gibraltar");
$states['Greece'] = construct_array("Thrakh,Makedonia,Hpeiros,Thessalia,Sterea-Ellada,Peloponnhsos,Nhsia-Aigaiou,Nhsia-Ioniou,Krhth");
$states['Greenland'] = construct_array("Kujalleq,Qaasuitsup,Qeqqata,Semersooq");
$states['Grenada'] = construct_array("Carriacou,Saint Andrew,Saint David,Saint George,Saint John,Saint Mark,Saint Patrick");
//$states['Guadeloupe'] = construct_array("Basse-Terre,Pointe-à-Pitre");
$states['Guam'] = construct_array("Agana Heights,Agat,Asan,Barrigada,Chalan-Pago-Ordot,Bededo,Hagåtña,Inarajan,Mangilao,Merizo,Mongmong-Toto-Maite,Piti,Santa Rita,Sinajana,Talofofo,Tamuning,Umatac,Yigo,Yona");
$states['Guatemala'] = construct_array("Alta Verapaz,Baja Verapaz,Chimaltenango,Chiquimula,El Progreso,Escuintla,Guatemala,Huehuetenango,Izabal,Jalapa,Jutiapa,Petén,Quetzaltenango,Quiché,Retalhuleu,Sacatepéquez,San Marcos,Santa Rosa,Sololá,Suchitepéquez,Totonicapán,Zacapa");
$states['Guinea'] = construct_array("Beyla,Boffa,Boké,Conakry,Coyah,Dabola,Dalaba,Dinguiraye,Dubréka,Faranah,Forécariah,Fria,Gaoual,Guéckédou,Kankan,Kérouané,Kindia,Kissidougou,Koubia,Koundara,Kouroussa,Labé,Lélouma,Lola,Macenta,Mali,Mamou,Mandiana,Nzérékoré,Pita,Siguiri,Télimélé,Tougué,Yomou");
$states['Guinea-Bissau'] = construct_array("Bafatá,Biombo,Bissau,Bolama,Cacheu,Gabú,Oio,Quinara,Tombali");
$states['Guyana'] = construct_array("Barima-Waini,Cuyuni-Mazaruni,Demerara-Mahaica,East Berbice-Corentyne,Essequibo Islands-West Demerara,Mahaica-Berbice,Pomeroon-Supenaam,Potaro-Siparuni,Upper Demerara-Berbice,Upper Takutu-Upper Essequibo");
$states['Haiti'] = construct_array("L'Artibonite,Centre,Grand' Anse,Nippes,Nord,Nord-Est,Nord-Ouest,Ouest,Sud,Sud-Est");
//$states['Heard-and-Mc-Donald-Islands'] = construct_array("Penguin Town");
$states['Vatican-City'] = construct_array("Vatican City");
$states['Honduras'] = construct_array("Atlántida,Choluteca,Colón,Comayugua,Copán,Cortés,El Paraíso,Francisco Morazán,Gracias a Dios,Intibucá,Islas de la Bahía,La Paz,Lempira,Ocotepeque,Olancho,Santa Bárbara,Valle,Yoro");
$states['Hungary'] = construct_array("Bács-Kiskun,Baranya,Békés,Borsod-Abaúj-Zemplén,Csongrád,Fejér,Győr-Moson-Sopron,Hajdú-Bihar,Heves,Jász-Nagykun-Szolnok,Komárom-Esztergom,Nógrád,Pest,Somogy,Szabolcs-Szatmár-Bereg,Tolna,Vas,Veszprém,Zala");
$states['Iceland'] = construct_array("Reykjavik,Keflavík,Borgarnes,Ísafjörður,Sauðárkrókur,Akureyri,Egilsstaðir,Selfoss");
$states['India'] = construct_array("Andaman and Nicobar Islands,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,Dadra and Nagar Haveli,Daman and Diu,Delhi,Goa,Gujarat,Haryana,Himachal Pradesh,Jammu and Kashmir,Jharkhand,Karnataka,Kerala,Lakshadweep,Madhya Pradesh,Maharashtra,Manipur,Meghalaya,Mizoram,Nagaland,Odisha,Puducherry,Punjab,Rajasthan,Sikkim,Tamil Nadu,Tripura,Uttarakhand,Uttar Pradesh,West Bengal");
$states['Indonesia'] = construct_array("Aceh,Bali,Bangka-Belitung,Banten,Bengkulu,Gorontalo,Jakarta Raya,Jambi,Jawa Barat,Jawa Tengah,Jawa Timur,Kalimantan Barat,Kalimantan Selatan,Kalimantan Tengah,Kalimantan Timur,Kalimantan Utara,Kepulauan Riau,Lampung,Maluku,Maluku Utara,Nusa Tenggara Barat,Nusa Tenggara Timur,Papua,Papua Barat,Riau,Sulawesi Barat,Sulawesi Selatan,Sulawesi Tengah,Sulawesi Tenggara,Sulawesi Utara,Sumatera Barat,Sumatera Selatan,Sumatera Utara,Yogyakarta");
$states['Iran'] = ["Iran"];
$states['Iraq'] = construct_array("Albor,Ardebil,Bushehr,Chahar Mahall and Bakhtiari,East Azarbaijan,Esfahan,Fars,Gilan,GOlestan,Hamadan,Hormozgan,Ilam,Kerman,Kermanshah,Khuzestan,Kohgiluyeh and Buyer Ahmad,Kordestan,Lerestan,Markazi,Mazandaran,North Khorasan,Qazvin,Qom,Razavi,Khorasan,Semnan,Sistan and Baluchestan,South Khorasan,Tehran,West Azarbajian,Yazd,Zanjan");
$states['Israel'] = construct_array("HaDarom,Haifa,HaMeraz,HaZafon,Jerusalem,Tel Aviv");
$states['Italy'] = construct_array("Agrigento,Alessandria,Ancona,Aosta,Arezzo,Ascoli Piceno,Asti,Avellino,Bari,Barletta-Andria-Trani,Belluno,Benevento,Bergamo,Biella,Bologna,Bolzano,Brescia,Brindisi,Cagliari,Caltanissetta,ampobasso,Carbonia-Iglesias,Caserta,Catania,Catanzaro,Chieti,Como,Cosenza,Cremona,Crotone,Cuneo,Enna,Fermo,Ferrara,Florence,Foggia,Forlì-Cesena,Foresinone,Genoa,Gorizia,Grosseto,Imperia,Isernia,L'Aquila,La Spezia,Latina,Lecce,Lecco,Livorno,Lodi,Lucca,Macerata,Mantua,Massa-Carrara,Matera,Medio Campidano,Messina,Milan,Modena, Monza e Brianza,Naples,Novara,Nouro, Ogliastra,Olbia-Tempio,Oristano,Padua,Palermo,Parma,Pavia,Perugia,Pesaro e Urbino,Pescara,Piacenza,Pisa,Pistoia,Prodenone,Potenza,Prato,Ragusa,Revenna,Reggio di Calabria,Reggio nell'Emillia,Rieti,Rimini,Rome,Rovigo,Salerno,Sassari,Savona,Siena,Sondrio,Syracuse,Taranto,Teramo,Terni,Trapani,Trento,Treviso,Trieste,Turin,Udine,Varese,Venice,Verbano-Cusio-Ossola,Vercelli,Verona,Vibo,Valentia,Vicenza,Viterbo");
$states['Jamaica'] = construct_array("Clarendon,Hanover,Kingston,Manchester,Portland,Saint Andrew,Saint Ann,Saint Catherine,Saint Elizabeth,Saint James,Saint Mary,Saint Thomas,Trelawny,Westmoreland");
$states['Japan'] = construct_array("Tokyo,Kanagawa,Osaka,Aichi,Chiba,Hyogo,Saitama,Hokkaido,Fukuoka,Shizuoka,Hiroshima,Kyoto,Ibaraki,Miyagi,Niigata,Tochigi,Nagano,Okayama,Gumma,Mie,Fukushima,Gifu,Yamaguchi,Kagoshima,Kumamoto,Ehime,Nagasaki,Okinawa,Aomori,Nara,Yamagata,Ishikawa,Oita,Iwate,Shiga,Toyama,Miyazaki,Akita,Wakayama,Fukui,Kagawa,Tokushima,Saga,Kochi,Shimane,Yamanashi,Tottori");
$states['Jordan'] = construct_array("Ajlun,Amman,Aqaba,Balqa,Irbid,Jarash,Karak,Ma`an ,Madaba,Mafraq,Tafilah,Zarqa");
$states['Kenya'] = construct_array("Baringo,Bomet,Bungoma,Busia,Elgeyo Marakwet,Embu,Garissa,Homa Bay,Isiolo,Kajiado,Kakamega,Kericho,Kiambu,Kilifi,Kirinyaga,Kisii,Kisumu,Kitui,Kwale,Laikipia,Lamu,Machakos,Makueni,Mandera,Marsabit,Meru,Migori,Mombasa,Murang'a,Nairobi,Nakuru,Nandi,Narok,Nyamira,Nyandarua,Nyeri,Samburu,Siaya,Taita Taveta,Tana River,Tharaka Nithi,Trans Nzoia,Turkana,Uasin Gishu,Vihiga,Wajir,West Pokot");
$states['Kiribati'] = construct_array("Gilbert Islands,Line Islands,Phoenix Islands");
$states['South-Korea'] = construct_array("Busan,Chungcheongbuk-do,Chungcheongnam-do,Dauegu,Daejeon,Gangwon-do,Gwangju,Gyeonggi-do,Gyeongsangbuk-do,Gyeongsangnam-do,Incheon,Jeju-do,Jeollabuk-do,Jeollanam-do,Sejong,Seoul,Ulsan");
$states['North-Korea'] = construct_array("Chagang-do,Hamgyŏng-bukto,Hamgyŏng-namdo,Hwanghae-bukto,Hwanghae-namdo,Kangwŏn-do,Najin Sŏnbong-si,P'yŏngan-bukto,P'yŏngan-namdo,P'yŏngyang-si,Yanggang-do");
$states['Kuwait'] = construct_array("Al Ahmadi,Farwānīyah,Al Jahrah,Al Kuwayt,Hawalli,Mubarakk Al-Kabir");
$states['Kyrgyzstan'] = construct_array("Batken,Bishkek,Chüy,Jalal-Abad,Naryn,Osh,Talas,Ysyk-Köl");
$states['Laos'] = construct_array("Attapu,Bokeo,Bolikhamxai,Champasak,Houaphan,Khammouan,Louang Namtha,Louangphrabang,Oudômxai,Phôngsali,Saravan,Savannakhét,Vientiane,Vientiane [Prefecture],Xaignabouri,Xékong,Xiangkhoang");
$states['Latvia'] = construct_array("Ādaži,Aglona,Aizkraukle,Aizpute,Aknīste,Aloja,Alsunga,Alūksne,Amata,Ape,Auce,Babīte,Baldone,Baltinava,Balvi,Bauska,Beverīna,Brocēni,Carnikava,Cēsis,Cesvaine,Cibla,Dagda,Daugavpils,Dobele,Dundaga,Durbe,Engure,Ērgļi,Garkalne,Grobina,Gulbene,Iecava,Ikšķile,Ilūkste,Inčukalns,Jaunjelgava,Jaunpiebalga,Jaunpils,Jēkabpils,Jelgava,Jūrmala,Kandava,Kārsava,Ķegums,Ķekava,Kocēnu,Koknese,Krāslava,Krimulda,Krustpils,Kuldīga,Lielvārde,Liepāja,Līgatne,Limbaži,Līvāni,Lubāna,Madona,Mālpils,Mārupe,Mazsalaca,Mērsraga,Naukšēni,Nereta,Nīca,Ogre,Olaine,Ozolnieki,Pārgauja,Pāvilosta,Pļaviņas,Preiļi,Priekule,Priekuļi,Rauna,Rēzekne,Riebiņi,Rīga,Roja,Ropaži,Rucava,Rugāji,Rūjiena,Rundāle,Sala,Salacgrīva,Salaspils,Saldus,Saulkrasti,Sēja,Sigulda,Skrīveri,Skrunda,Smiltene,Stopiņi,Strenči,Talsi,Tērvete,Tukums,Vaiņode,Valka,Valmiera,Varakļāni,Vārkava,Vecpiebalga,Vecumnieki,Ventspils,Viesīte,Viļaka,Viļāni,Zilupe");
$states['Lebanon'] = construct_array("Aakkar,An Nabaţīyah,Baalbek-Hermel,Beirut,Beqaa,Mount Lebanon,North Lebanon,South Lebanon");
$states['Lesotho'] = construct_array("Berea,Butha-Buthe,Leribe,Mafeteng,Maseru,Mohale's Hock,Mokhotlong,Qacha's Nek,Quthing,Thaba-Tseka");
$states['Liberia'] = construct_array("Bomi,Bong,Gbarpolu,Grand Bassa,Grade Cape Mount,Grand Gedeh,Grand Kru,Lofa,Margibi,Maryland,Monstserrado,Nimba,Rivercess,River Gee,Sinoe");
$states['Libya'] = construct_array("Al Butnan,Al Jabal al Akhdar,AlJabal al Gharbi,Al Jifarah,AlJufrah,Al Kufrah,Al Marj,Al Marqab,Al Wahat,An Nuqat al Khams,Az Zawiyah,Benghazi,Darnah,Ghat,Misratah,Murzuq,Nalut,Sabha,Surt,Tripoli,Wadi al Hayat,Wadi ash Shati'");
$states['Liechtenstein'] = construct_array("Balzers,Eschen,Gamprin,Mauren,Planken,Ruggell,Schaan,Schellenberg,Triesen,Triesenberg,Vaduz");
$states['Lithuania'] = construct_array("Alytaus apskritis,Kauno apskritis,Klaipedos apskritis,Marijampoles apskritis,Panevežio apskritis,Šiauliu apskritis,Taurages apskritis,Telšiu apskritis,Utenos apskritis,Vilniaus apskritis");
$states['Luxembourg'] = construct_array("Diekirch,Grevenmacher,Luxembourg");
$states['Macedonia'] = construct_array("Aerodrom,Aračinovo,Berovo,Bitola,Bogdanci,Bogovinje,Bosilovo,Brvenica,Butel,Centar,Centar Župa,Čair,Čaška,Češinovo-Obleševo,Čučer Sandevo,Debar,Debartsa,Delčevo,Demir Hisar,Demir Kapija,Dojran,Dolneni,Drugovo,Gazi Baba,Gevgelija,Gjorče Petrov,Gostivar,Gradsko,Ilinden,Jegunovtse,Karbinci,Karpoš,Kavadartsi,Kičevo,Kisela Voda,Kočani,Konče,Kratovo,Kirva Palanka,Krivogaštani,Kruševo,Kumanovo,Lipkovo,Lozovo,Makedonska Kamenica,Makedonski Brod,Mavrovo and Rostuša,Mogila,Negotino,Novatsi,Novo Selo,Ohrid,Oslomej,Pehčevo,Petrovec,Plasnica,Prilep,Probištip,Radoviš,Rankovce,Resen,Rosoman,Saraj,Štip,Šuto Orizari,Sopište,Staro Nagoričane,Struga,Strumitsa,Studeničani,Sveti Nikole,Tearce,Tetovo,Valandovo,Vasilevo,Veles,Vevčani,Vinitsa,Vraneštica,Vrapčište,Zajas,Zelenikovo,Želino,Zrnovci");
$states['Madagascar'] = construct_array("Alaotra Mangoro,Amoron'i Mania,Analamanga,Analanjirofo,Androy,Anosy,Atsimo-Andrefana,Atsimo-Atsinanana,Atsinanana,Betsiboka,Boeny,Bongolava,Diana,Haute Matsiatra,Ihorombe,Itasy,Melaky,Menabe,Sava,Sofia,Vakinankaratra,Vatovavy Fitovinany");
$states['Malawi'] = construct_array("Balaka,Blantyre,Chikwawa,Chiradzulu,Chitipa,Dedza,Dowa,Karonga,Kasungu,Likoma,Lilongwe,Machinga,Mangochi,Mchinji,Mulanje,Mwanza,Mzimba,Neno,Nkhata Bay,Nkhotakota,Nsanje,Ntcheu,Ntchisi,Phalombe,Rumphi,Salima,Thyolo,Zomba");
$states['Malaysia'] = construct_array("Perlis,Penang,Kedah,Terrenganu,Kelantan,Perak,Pahang,Negeri Sembilan,Selangor,Wilayah Persekutuan,Melaka,Johor,Sarawak,Sabah");
$states['Maldives'] = construct_array("Addu,Aliff Aliff,Aliff Daalu,Baa,Daalu,Faafu,Gaafu Aliff,Gaafu Daalu,Haa Aliff,Haa Daalu,Kaafu,Laamu,Laviyani,Male,Meemu,Naviyani,Noonu,Raa,Shaviyani,Thaa,Waavu");
$states['Mali'] = construct_array("Bamako,Gao,Kayes,Kidal,Koulikoro,Mopti,Ségou,Sikasso,Timbuktu");
$states['Malta'] = construct_array("Central,Gozo,Northern,South Eastern,Southern");
$states['Marshall-Islands'] = construct_array("Marshall Islands");
$states['Martinique'] = construct_array("Carriacou,Saint Andrew,Saint David,Saint George,Saint John,Saint Mark,Saint Patrick");
$states['Mauretania'] = construct_array("Adrar,Assaba,Brakna,Dakhlet Nouadhibou,Gorgol,Guidimaka,Hodh ech Chargui,Hodh el Gharbi,Inchiri,Nouakchott,Tagant,Tiris,Zemmour,Trarza");
$states['Mauritius'] = construct_array("Agalega Islands,Black River,Cargados Carajos,Flacq,Grand Port,Moka,Pamplemousses,Plaines Wihems,Port Louis,Rivière du Rempart,Rodrigues,Savanne");
//$states['Mayotte'] = construct_array("Acoua,Bandraboua,Bandrélé,Bouéni,Chiconi,Chirongui,Dembeni,Dzaoudzi,Kani-Kéli,Koungou,Maoudzou,Mtsamboro,M'Tsangamouji,Ouangani,Pamandzi,Sada,Tsingoni");
$states['Mexico'] = construct_array("Aguascalientes,Baja California,Baja California Sur,Campeche,Chiapas,Chihuahua,Coahuila,Colima,Distrito Federal,Durango,Guanajuato,Guerrero,Hidalgo,Jalisco,México,Michoacán,Morelos,Nayarit,Nuevo Leon,Oaxaca,Puebla,Querétaro,Quintana Roo,San Luis Potosf,Sinaloa,Sonora,Tabasco,Tamaulipas,Tlaxcala,Veracruz,Yucatán,Zacatecas");
$states['Micronesia'] = construct_array("Chuuk,Kosrae,Pohnpei,Yap");
$states['Moldova'] = construct_array("Anenii Noi,Bălţi,Basarabeasca,Bender,Briceni,Cahul,Călăraşi,Cantemir,Căuşeni,Chişinău,Cimişlia,Criuleni,Donduşeni,Drochia,Dubăsari,Edineţ,Făleşti,Floreşti,Găgăuzia,Glodeni,Hînceşti,Ialoveni,Leova,Nisporeni,Ocniţa,Orhei,Rezina,Rîşcani,Sîngerei,Şoldăneşti,Soroca,Ştefan Vodă,Străşeni,Taraclia,Teleneşti,Transnistria,Ungheni");
$states['Monaco'] = construct_array("Monaco");
$states['Mongolia'] = construct_array("Arhangay,Bayanhongor,Bayan-Ölgiy,Bulgan,Darhan-Uul,Dornod,Dornogovi,Dundgovi,Dazvhan,Govi-Altay,Govisumber,Henity,Hovd,Hövsgöl,Ömnögovi,Orhon,Övörhangay,Selenge,Sühbaatar,Töv,Ulaanbaatar");
$states['Montserrat'] = construct_array("Saint Anthony,Saint Georges,Saint Peter");
$states['Morocco'] = construct_array("Chaouia - Ouardigha,Doukkala - Abda,Fès - Boulemane,Gharb - Chrarda - Béni Hssen,Grand Casablanca,Guelmim - Es-Semara,Laâyoune - Boujdour - Sakia El Hamra,Marrakech - Tensift - Al Haouz,Meknès - Tafilalet,Oriental,Oued Ed-Dahab - Lagouira,Rabat - Salé - Zemmour - Zaer,Souss - Massa - Draâ,Tadla - Azilal,Tanger - Tétouan,Taza - Al Hoceima - Taounate");
$states['Mozambique'] = construct_array("Cabo Delgado,Gaza,Inhambane,Manica,Maputo,Maputo City,Nampula,Niassa,Sofala,Tete,Zambézia");
$states['Myanmar'] = construct_array("Ayeyarwady,Bago,Chin,Kachin,Kayah,Kayin,Magway,Mandalay,Mon,Naypyidaw,Rakhine,Sagaing,Shan,Tanintharyi,Yangon");
$states['Namibia'] = construct_array("Erongo,Hardap,Karas,Kavango East,Kavango West,Khomas,Kunene,Ohangwena,Omaheke,Omusati,Oshana,Oshikoto,Otjozondjupa,Zambezi");
$states['Nauru'] = construct_array("Aiwo,Anabar,Anetan,Anibare,Baiti,Boe,Buada,Denigomodu,Ewa,Ijuw,Meneng,Nibok,Uaboe,Yaren");
$states['Nepal'] = construct_array("Achham,Argakhanchi,Baglung,Baitadi,Bajhang,Bajura,Banke,Bara,Bardiya,Bhaktapur,Bhojpur,Chitwan,Dadeldhura,Dailekh,Dang Deokhuri,Darchula,Dhading,Dhankuta,Dhanusa,Dolkha,Dolpa,Doti,Gorkha,Gulmi,Humla,Ilam,Jajarkot,Jhapa,Jumla,Kailali,Kalikot,Kanchanpur,Kapilvastu,Kaski,Kathmandu,Kavrepalanchok,Khotang,Lalitpur,Lamjung,Mahottari,Makwanpur,Manang,Morang,Mugu,Mustang,Myagdi,Nawalparasi,Nuwakot,Okhaldhunga,Palpa,Panchthar,Parbat,Parsa,Pyuthan,Ramechhap,Rasuwa,Rautahat,Rolpa,Rukum,Rupandehi,Salyan,Sankhuwasabha,Saptari,Sarlahi,Sindhuli,Sindhupalchok,Siraha,Solukhumbu,Sunsari,Surkhet,Syangja,Tanahu,Taplejung,Terhathum,Udayapur");
$states['Netherlands'] = construct_array("Groningen,Friesland,Drenthe,Overijssel,Flevoland,Gelderland,Utrecht,Noord-Holland,Zuid-Holland,Zeeland,Noord-Brabant,Limburg");
$states['Netherlands-Antilles'] = construct_array("Bonaire,Curaçao,Saba,Sint Eustatius,Sint Eustatius,Sint Maarten");
$states['New-Caledonia'] = construct_array("Îles Loyauté,Nord,Sud");
$states['New-Zealand'] = construct_array("Auckland,Bay of Plenty,Canterbury,Chatham Islands,Gisborne,Hawke's Bay,Manawatu-Wanganui,Marlborough,Nelson,Northland,Otago,Southland,taranaki,Tasman,Waikato,Wellington,West Coast");
$states['Nicaragua'] = construct_array("Boaco,Carazo,Chinandega,Chontales,Estelí,Granada,Jinotega,León,Madriz,Managua,Masaya,Matagalpa,Neuva Segovia,Región Autónoma del Atlántico Norte,Región Autónoma del Atlántico Sur,Río San Juan,Rivas");
$states['Niger'] = construct_array("Agadez,Diffa,Dosso,Maradi,Niamey,Tahoua,Tillabéri,Zinder");
$states['Nigeria'] = construct_array("Abia,Adamawa,Akwa Ibom,Anambra,Bauchi,Bayelsa,Benue,Borno,Cross River,Delta,Ebonyi,Edo,Ekiti,Enugu,Federal Capital Territory,Gombe,Imo,Jigawa,Kaduna,Kano,Katsina,Kebbi,Kogi,Kwara,Lagos,Nassarawa,Niger,Ogun,Ondo,Osun,Oyo,Plateau,Rivers,Sokoto,Taraba,Yobe,Zamfara");
$states['Niue'] = construct_array("Niue");
$states['Norfolk-Islands'] = construct_array("Norfolk Island");
$states['Northern-Mariana-Islands'] = construct_array("Northern Mariana Islands");
$states['Norway'] = construct_array("Akershus,Aust-Agder,Buskerud,Finnmark,Hedmark,Hordaland,Møre og Romsdal,Nordland,Nord-Trøndelag,Oppland,Oslo,Østfold,Rogaland,Sogn og Fjordane,Sør-Trøndelag,Telemark,Troms,Vest-Agder,Vestfold");
$states['Oman'] = construct_array("Adam,Ad Duqm,Al Amrat,Al Awabi,Al Buraymi,Al Hamra,Al Jazer,Al Kamil Wa Al Wafi,Al Khaburah,Al Mazyunah,Al Mudaybi,Al Musanaah,Al Qabil,Ar Rustaq,As Seeb,As Sunaynah,As Suwayq,Bahla,Barka,Bawshar,Bid Bid,Bidiyah,Bukha,Daba,Dalkut,Dama Wa At Taiyyin,Dank,Hayma,Ibra,Ibri,Izki,Jaalan Bani Bu Ali,Jaalan Bani Bu Hasan,Khasab,Liwa,Madha,Mahadah,Mahat,Manah,Masirah,Mirbat,Muqshin,Muscat,Mutrah,Nakhal,Nizwa,Qurayyat,Rakhyut,Sadah,Saham,Salalah,Samail,Shalim Wa Juzur Al Hallaniyat,Shinas,Sohar,Sur,Taqah,Thumrayt,Wadi Al Maawil,Wadi Bani Khalid,Yanqul");
$states['Pakistan'] = construct_array("Azad Kashmir,Bahawalpur,Bannu,Dera Ghazi Khan,Dera Ismail Khan,Faisalabad,F.A.T.A,Gujranwala,Hazara,Hyderabad,Islamabad,Kalat,Karachi,Kohat,Lahore,Larkana,Makran,Malakand,Mardan,Mirpur Khas,Multan,Nasirabad,Northern Areas,Peshawar,Quetta,Rawalpindi,Sargodha,Sibi,Sukkur,Zhob");
$states['Palau'] = construct_array("Aimeliik,Airai,Angaur,Hatohobei,Kayangel,Koror,Melekeok,Ngaraard,Ngarchelong,Ngardmau,Ngatpang,Ngchesar,Negeremlengui,Ngiwal,Peleliu,Sonsorol");
$states['Panama'] = construct_array("Bocas del Toro,Chiriquí,Coclé,Colón,Darién,Emberá,Herrera,Kuna de Madungandí,Kuna de Wargandí,Kuna Yala,Los Santos,Ngäbe Buglé,Panamá,Veraguas");
$states['Papua-New-Guinea'] = construct_array("Bougainville,Central,Chumbu,Eastern Highlands,East New Britain,Est Sepik,Enga,Gulf,Hela,Jiwaka,Madang,Manus,Milne Bay,Morobe,National Capital District,New Ireland,Northern,Sandaun,Southern Highlands,Western,Western Highlands,West New Britain");
$states['Paraguay'] = construct_array("Alto Paraguay,Alto Paraná,Amambay,Asunción,Boquerón,Caaguazú,Caazapá,Canindeyú,Central,Concepción,Cordillera,Guairá,Itapúa,Misiones,Ñeembucú,Paraguarí,Presidente Hayes,San Pedro");
$states['Peru'] = construct_array("Amazonas,Ancash,Apurímac,Arequipa,Ayacucho,Cajamarca,Callao,Cusco,Huancavelica,Huánuco,Ica,Junín,La Libertad,Lambayeque,Lima,Loreto,Madre de Dios,Pasco,Piura,Puno,San Martín,Tacna,Tumbes,Ucayali");
$states['Philippines'] = construct_array("Abra,Agusan del Norte,Agusan del Sur,Aklan,Albay,Antique,Apayao,Aurora,Basilan,Bataan,Batanes,Batangas,Benguet,Biliran,Bohol,Bukidnon,Bulacan,Cagayan,Camarines Norte,Camarines Sur,Camiguin,Capiz,Catanduanes,Cavite,Cebu,Compostela Valley,Catabato,Davao del Norte,Davao del Sur,Davao Occidental,Davao Oriental,Dinagat Islands,Eastern Samar,Guimaras,Ifugao,Ilocos Norte,Ilocos Sur,Iloilo,Isabela,Kalinga,Laguna,Lanao del Norte,Lanao del Sur,La Union,Leyte,Maguindanao,Marinduque,Masbate,Metropolitan Manila,Misamis Occidental,Misamis Oriental,Mountain,Negros Occidental,Negros Oriental,Northern Samar,Nueva Ecija,Nueva Vizcaya,Occidental Mindoro,Oriental Mindoro,Palawan,Pampanga,Pangasinan,Quezon,Qurino,Rizal,Romblon,Samar,Sarangani,Siquijor,Sorsongan,South Cotabato,Southern Leyte,Sultan Kudarat,Sulu,Surigao del Norte,Surigao del Sur,Tarlac,Tawi-Tawi,Zambales,Zamboanga del Norte,Zamboanga del Sur,Zamboanga-Sibugay");
$states['Pitcairn-Islands'] = construct_array("Pitcairn Islands");
$states['Poland'] = construct_array("Dolnoslaskie,Kujawsko-Pomorskie,Lubelskie,Lubuskie,Lodzkie,Malopolskie,Mazowieckie,Opolskie,Podkarpackie,Podlaskie,Pomorskie,Slaskie,Swietokrzyskie,Warminsko-mazurskie,Wielkopolskie,Zachodniopomorskie");
$states['Portugal'] = construct_array("Aveiro,Azores,Beja,Braga,Bragança,Castelo Branco,Coimbra,Évora,Faro,Guarda,Leiria,Lisboa,Madeira,Portalegre,Porto,Santarém,Setúbal,Viana do Castelo,Vila Real,Viseu");
$states['Puerto-Rico'] = construct_array("Adjuntas,Aguada,Aguadilla,Aguas Beunas,Aibonito,Añasco,Arecibo,Arroyo,Barceloneta,Barranquitas,Bayamón,Cabo ROjo,Caguas,Camuy,Canóvanas,Carolina,Cataño,Cayey,Ceiba,Ciales,Cidra,Coamo,Comerío,Corozal,Culebra,Dorado,Fajardo,Florida,Guánica,Guayama,Guayanilla,Guaynabo,Gurabo,Hatillo,Hormigeuros,Humacao,Isabela,Jayuya,Juana Díaz,Juncos,Lajas,Lares,Las Marías,Las Piedras,Loíza,Luquillo,Manatí,Maricao,Maunabo,Mayagüez,Moca,Morovis,Naguabo,Naranjito,Orocovis,Patillas,Peñuelas,Ponce,Quebradillas,Rincón,Río Grande,Sabana Grande,Salinas,San Germán,San Juan,San Lorenzo,San Sebastián,Santa Isabel,Toa Alta,Toa Baja,Trujillo Alto,Utuado,Vega Alta,Vieques,Villalba,Yabucoa,Yauco");
$states['Qatar'] = construct_array("Ad Dawhah,Al Daayen,Al Khawr,Al Wakrah,Ar Rayyan,Madinat ach Shamal,Umm Salal");
$states['Qazaqstan'] = construct_array("Алматы,Астана,Актау,Актобе,Атырау,Караганда,Кокшетау,Костанай,Кызылорда,Павлодар,Петропавловск,Семей,Талдыкорган,Тараз,Туркестан,Уральск,Усть-Каменогорск,Шымкент");
$states['Romania'] = construct_array("Alba,Arad,Arges,Bacau,Bihor,Bistrita-Nasaud,Botosani,Brasov,Braila,Bucuresti,Buzau,Calarasi,Caras-Severin,Cluj,Constanta,Covasna,Dambovita,Dolj,Galati,Giurgiu,Gorj,Harghita,Hunedoara,Ialomita,Iasi,Ilfov,Maramures,Mehedinti,Mures,Neamt,Olt,Prahova,Satu Mare,Salaj,Sibiu,Suceava,Teleorman,Timis,Tulcea,Vaslui,Valcea,Vrancea");
$states['Russia'] = construct_array("Buryat Autonomous district,Republic of Adygea,Altay krai,Amur region,Arkhangelsk region,Astrakhan region,Republic of Bashkortostan,Belgorod region,Bryansk region,Republic of Buryatia,Vladimir region,Volgograd region,Vologda region,Voronezh region,Republic of Altai,Republic of Dagestan,Jewish Autonomous region,Ivanovo region,Republic of Ingush,Irkutsk region,Kabardino-Balkaria,Kaliningrad region,Republic of Kalmykia,Kaluga region,Kamchatka,Republic of Karachay-Cherkess,Republic of Karelia,Kemerovo region,Kirov region,Republic of Komi,Komi-Perm Autonomous district,Koryak Autonomous district,Kostroma region,Krasnoyarsk krai,Kurgan region,Kursk region,Leningrad region,Lipetsk region,Magadan region,Republic of Mari El,Republic of Mordovia,Moscow,Moscow region,Murmansk region,Nenets Autonomous district,Nizhny Novgorod region,Novgorod region,Novosibirsk region,Omsk region,Orenburg region,Orel region,Penza region,Perm region,Primorsky Krai,Pskov region,Rostov region,Ryazan region,Samara region,Saint Petersburg,Saratov region,Republic of Sakha (Yakutia),Sakhalin region,Sverdlovsk region,Republic of North Ossetia,Smolensk region,Stavropol region,Taimyr (Dolgan-Nenets) Autonomous district,Tambov region,Republic of Tatarstan,Tver region,Tomsk region,Republic of Tuva (Tyva),Tula region,Tyumen region,Udmurtia region,Ulyanovsk region,Ust-Orda Buryat Autonomous district,Khabarovsk krai,Republic of Khakassia,Khanty Mansiysk Autonomous district,Chelyabinsk region,Republic of Chechen,Chita region,Republic of Chuvash,Chukotka Autonomous district,Evenki Autonomous district,Yamal-Nenets Autonomous district,Yaroslavl region,Republic of Crimea,Sevastopol' City");
$states['Rwanda'] = construct_array("Eastern,Kigali City,Northern,Southern,Western");
$states['Saint-Kitts-and-Nevis'] = construct_array("Christ Church Nichola Town,Saint Anne Sandy Point,Saint George Bassaterre,Saint George Gingerland,Saint James Windward,Saint John Capisterre,Saint John Figtree,Saint Mary Cayon,Saint Paul Capisterre,Saint Paul Charlestown,Saint Peter Basseterre,Saint Thomas Lowland,Saint Thomas Middle Island,Trinity Palmetto Point");
$states['Saint-Lucia'] = construct_array("Anse-la-Raye,Canaries,Castries,Choiseul,Dennery,Gros Islet,Laborie,Micoud,Soufrière,Vieux Fort");
$states['Saint-Vincent-and-Grenadines'] = construct_array("Charlotte,Grenadines,Saint Andrew,Saint David,Saint George,Saint Patrick");
$states['Samoa'] = construct_array("A`ana,Aiga-i-le-Tai,Atua,Fa`asaleleaga,Gaga`emauga,Gagaifomauga,Palauli,Satupa`itea,Tuamasaga,Va`a-o-Fonoti,Vaisigano");
$states['San-Marino'] = construct_array("Acquaviva,Borgo Maggiore,Chiesanuova,Damagnano,Faetano,Fiorentino,Montegiardino,San Marino,Serravalle");
$states['Sao-Tome-and-Principe'] = construct_array("Príncipe,São Tomé");
$states['Saudi-Arabia'] = construct_array("Al Bāhah,Al Ḥudūd ash Shamāliyah,Al Jawf,Al Madīnah,Al Qaṣīm,Ar Riyāḍ,Ash Sharqīyah,`Asīr,Ḥā'il,Jīzan,Makkah,Najrān,Tabūk");
$states['Senegal'] = construct_array("Bakel,Bambey,Bignona,Birkilane,Bounkiling,Dagana,Dakar,Diourbel,Fatick,Foundiougne,Gossas,Goudiry,Goudomp,Guédiawaye,Guinguinéo,Kaffrine,Kanel,Kaolack,Kébémer,Kédougou,Kolda,Koumpentoum,Koungheul,Linguère,Louga,Malème Hodar,Matam,Mbacké,Mbour,Médina Yoro Foula,Nioro du Rip,Oussouye,Pikine,Podor,Ranérou Ferlo,Rufisque,Saint-Louis,Salémata,Saraya,Sédhiou,Tambacounda,Thiès,Tivaouane,Vélingara,Ziguinchor");
$states['Seychelles'] = construct_array("Anse aux Pins,Ans Boileau,Anse Étoile,Anse Royale,Au Cap,Baie Lazare,Baie Sainte Anne,Beau Vallon,Bel Air,Belombre,Cascade,English River,Glacis,Grand' Anse (Mahe),Grand' Anse (Praslin),La Digue and Inner Islands,Les Mamelles,Mont Buxton,Mont Fleuri,Outer Islands,Plaisance,Pointe La Rue,Port Glaud,Roche Caïman,Saint Louis,Takamaka");
$states['Sierra Leone'] = construct_array("Bo,Bombali,Bonthe,Kailahun,Kambia,Kenema,Koinadugu,Kono,Moyamba,Port Loko,Pujehun,Sherbro Urban,Tonkolili,Western Rural,Western Urban");
$states['Singapore'] = construct_array("Singapore");
$states['Slovakia'] = construct_array("Banská Bystrica,Bratislava,Košice,Nitra,Prešov,Trencín,Trnava,Žilina");
$states['Slovenia'] = construct_array("Dolenjska,Gorenjska,Goriška,Koroška,Notranjsko-kraška,Obalno-kraška,Osrednjeslovenska,Podravska,Pomurska,Savinjska,Spondnjeposavska,Zasavska");
$states['Solomon-Islands'] = construct_array("Capital Territory,Central,Choiseul,Guadalcanal,Isabel,Makira,Malita,Rennel and Bellona,Temotu,Western");
$states['Somalia'] = construct_array("Somaliland,Puntland,Galmudug,Zelia & Lughaya State,Awdalland,Himan and Heeb,Khatumo State,Jubaland");
$states['South-Africa'] = construct_array("Eastern Cape,Free State,Gauteng,KwaZulu-Natal,Limpopo,Mpumalanga,Northern Cape,North-West,Western Cape");
$states['South-Georgia'] = construct_array("South Georgia and the South Sandwich Islands");
$states['Spain'] = construct_array("Andalusia,Aragon,Asturias,Balearic Islands,Basque Country,Canary Islands,Cantabria,Castile and Leon,Castile-La Mancha,Catalonia,Ceuta,Extremadura,Galicia,La Rioja,Madrid,Melilla,Murcia,Navarra,Valencia");
$states['Sri-Lanka'] = construct_array("Ampara,Anarudhapura,Badulla,Batticaloa,Colombo,Galle,Gampaha,Hambantota,Jaffna,Kalutara,Kandy,Kegalle,Kilinochchi,Kurunegala,Mannar,Matale,Matara,Moneragala,Mullaitivu,Nuwara Eliya,Polonnaruwa,Puttalam,Ratnapura,Trincomalee,Vavuniya");
//$states['St.-Helena'] = construct_array("Ascension,Saint Helena,Tristan da Cunha");
//$states['St.-Pierre-and-Miquelon'] = construct_array("Miquielon-Langlade,Saint-Pierre");
$states['Sudan'] = construct_array("Blue Nile,Central Darfur,East Darfur,Gedarif,Gezira,Kassala,Khartoum,North Darfur,Northern,North Kordofan,Red Sea,River Nile,Sennar,South Darfur,South Kordofan,West Darfur,West Kordofan,White Nile");
$states['Suriname'] = construct_array("Brokopondo,Commewijne,Coronie,Marowijne,Nickerie,Para,Paramaribo,Saramacca,Sipaliwini,Wanica");
//$states['Svalbard-and-Jan-Mayen-Islands'] = construct_array("Jan Mayen,Svalbard");
$states['Swaziland'] = construct_array("Hhohho,Lubombo,Manzini,Shiselweni");
$states['Sweden'] = construct_array("Blekinge,Bohuslän,Dalarna,Dalsland,Lappland,Gotland,Gästrikland,Halland,Hälsingland,Jämtland,Närke,Medelpad,Norrbotten,Härjedalen,Skåne,Södermanland,Småland,Stockholm,Uppland,Värmland,Västerbotten,Västernorrland,Västmanland,Västergötland,Ångermanland,Öland,Östergötland");
$states['Switzerland'] = construct_array("Aargau,Appenzell Ausser-Rhoden,Appenzell Inner-Rhoden,Basel-Landschaft,Basel-Stadt,Bern,Fribourg,Geneve,Glarus,Graubunden,Jura,Luzern,Neuchatel,Nidwalden,Obwalden,Sankt Gallen,Schaffhausen,Schwyz,Solothurn,Thurgau,Ticino,Uri,Valais,Vaud,Zug,Zurich");
$states['Syria'] = construct_array("Aleppo,Al Hasakah,Ar Raqqah,As Suwaydā',Damascus,Dar`ā,Dayr az Zawr,Hama,Hims,Idlib,Latakia,Quneitra,Rif Dimashq,Ţarţūs");
$states['Taiwan'] = construct_array("Changhwa,Chiayi,Chiayi City,Hsinchu,Hsinchu City,Hualien,Ilan,Kaohsiung City,Keelung City,Kinmen,Lienkiang,Miaoli,Nantou,New Taipei City,Penghu,Pingtung,Taichung City,Tainan City,Taipei City,Taitung,Taoyuan,Yunlin");
$states['Tajikistan'] = construct_array("Ajninskij,Ashtskij,Babodzhon Gafurova,Bal’dzhuvonskij,Beshkentskij,Bohtarskij,Chkalovsk,Dangarinskij,Darbandskij,Darvozskij,Dzhilinkul’skij,Dzhirgatal’skij,Fajzabadskij,Frunzenskij,Ganchinskij,Garmskij,Gissarskij,Gozimanlikskij,Hodzhamastonskij,Horog,Hovalingskij,Hudzhand,imeni Dzhabbera Rasulova,Isfara,Isfarinskij,Ishkashimskij,Javanskij,Kabodijonskij,Kajrakkum,Kanibadam,Kanibadamskij,Kofarnihon,Kofarnihonskij,Kolhozabadskij,Kuhistoni Mastchohskij,Kuljab,Kuljabskij,Kumsangirskij,Kurgan-Tjube,Leninskij,Matchinskij,Moskovskij,Muminobodskij,Murgabskij,Nauskij,Nurek,Nurekskij,Oktjabr’skij,Parharskij,Pendzhikent,Pendzhikentskij,Pjandzheskij,Rogun,Rogunskij,Roshtkalinskij,Rushanskij,Sarband,Sarbandskij,Shaartuzskij,Shahrinavskij,Shahristanskij,Shugnanskij,Shuroobodskij,Sovetskij,Taboshar,Tadzhikabadskij,Tavildarinskij,Tsentral’nyj,Tursunzade,Tursunzadevskij,Ura-Tjube,Ura-Tjubinskij,Vahshskij,Vanchskij,Varzobskij,Vosejskij,Zafarobodskij,Zheleznodorozhnyj");
$states['Tanzania'] = construct_array("Arumeru,Arusha,Babati,Bagamoyo,Bariadi,Biharamulo,Bukoba Rural,Bukoba Urban,Bukombe,Bunda,Chake,Chunya,Dodoma Rural,Dodoma Urban,Geita,Hai,Hanang,Handeni,Igunga,Ilala,Ileje,Ilemela,Iramba,Iringa Rural,Iringa Urban,Kahama,Karagwe,Karatu,Kaskazini - Mkokotoni Kaskazini - Donge Mbiji Kasulu,Kati,Kibaha,Kibondo,Kigoma Rural,Kigoma Urban,Kilindi,Kilolo,Kilombero,Kilosa,Kilwa,Kinondoni,Kisarawe,Kishapu,Kiteto,Kondoa,Kongwa,Korogwe,Kusini,Kwimba,Kyela,Lindi Rural,Lindi Urban,Liwale,Ludewa,Lushoto,Mafia,Magharibi,Magu,Makete,Manyoni,Masasi,Maswa,Mbarali,Mbeya Rural,Mbeya Urban,Mbinga,Mbozi,Mbulu,Meatu,Micheweni,Misungwi,Mjini,Mkoani,Mkuranga,Monduli,Morogoro Rural,Morogoro Urban,Moshi Rural,Moshi Urban,Mpanda,Mpwapwa,Mtwara Rural,Mtwara Urban,Mufindi,Muheza,Muleba,Musoma Rural,Musoma Urban,Mvomero,Mwanga,Nachingwea,Namtumbo,Newala,Ngara,Ngorongoro,Njombe,Nkasi,Nyamagana,Nzega,Pangani,Rombo,Ruangwa,Rufiji,Rungwe,Same,Sengerema,Serengeti,Shinyanga Rural,Shinyanga Urban,Sikonge,Simanjiro,Singida Rural,Singida Urban,Songa Rural,Songea Urban,Sumbawanga Rural,Sumbawanga Urban,Tabora Urban,Tandahimba,Tanga,Tarime,Temeke,Tunduru,Ukerewe,Ulanga,Urambo,Uyui,Wete");
$states['Thailand'] = construct_array("Amnat Charoen,Ang Thong,Bangkok Metropolis,Bueng Kan,Buri Ram,Chachoengsao,Chai Nat,Chaiyaphum,Chanthaburi,Chiang Mai,Chiang Rai,Chon Buri,Chumphon,Kalasin,Kamphaeng Phet,Kanchanaburi,Khon Kaen,Krabi,Lampang,Lamphun,Loei,Lop Buri,Mae Hong Son,Maha Sarakham,Mukdahan,Nakhon Nayok,Nakhon Pathom,Nakhon Phanom,Nakhon Ratchasima,Nakhon Sawan,Nakhon Si Thammarat,Nan,Narathiwat,Nong Bua Lam Phu,Nong Khai,Nonthaburi,Pathum Thani,Pattani,Phangnga,Phantthalung,Phayao,Phetchabun,Phetchaburi,Phichit,Phitsanulok,Phrae,Phra Nakhon Si Ayutthaya,Phuket,Prachin Buri,Prachuap Khiri Khan,Ranong,Ratchaburi,Rayong,Roi Et,Sa Kaeo,Sakon Nakhon,Samut Prakan,Samut Sakhon,Samut Songkhram,Saraburi,Satun,Sing Buri,Si Sa Ket,Songkhla,Sukhothai,Suphan Buri,Surat Thani,Surin,Tak,Trang,Trat,Ubon Ratchathani,Udon Thani,Uthai Thani,Uttaradit,Yala,Yasothon");
$states['Timor-Leste'] = construct_array("Aileu,Ainaro,Alas,Atabae,Atauro,Atsabe,Baguia,Balibó,Barique-Natarbora,Baucau,Bazartete,Bobonaro,Cailaco,Cristo Rei,Dom Aleixo,Ermera,Fatuberliu,Fatululic,Fatumean,Fohoren,Hatólia,Hatu Builico,Hatu Udo,Iliomar,Lacló,Laclubar,Lacluta,Laga,Laleia,Laulara,Lautém,Lequidoe,Letefoho,Liquiçá,Lolotoe,Lospalos,Luro,Maliana,Manatuto,Mape-Zumalai,Maubara,Maubisse,Maucatar,Metinaro,Nain Feto,Nitibe,Oesilo,Ossu,Pante Macassar,Passabe,Quelicai,Railaco,Remexio,Samé,Soibada,Suai,Tilomar,Turiscai,Tutuala,Uatucarbau,Uatulari,Vemasse,Venilale,Vera Cruz,Viqueque");
$states['Togo'] = construct_array("Agou,Akébou,Amou,Anié,Assoli,Avé,Bas-Mono,Bassar,Binah,Blitta,Cinkassé,Dankpen,Danyi,Doufelgou,Est-Mono,Golfe,Haho,Kéran,Kloto,Kozah,Kpélé,Kpendjal,Lacs,Moyen-Mono,Ogou,Oti,otouboua,Tandjouaré,chamba,Tchaoudjo,Tône,Vo,Wawa,Yoto,Zio");
//$states['Tokelau'] = construct_array("Atafu,Fakaofo,Nukunonu");
$states['Tonga'] = construct_array("'Eua Fo'ou,'Eua Motu',Foa,Ha'ano,Hahake,Hihifo,Kolofo'ou,Kolomotu'a,Kolovai,Lapaha,Leimatu'a,Lulunga,Motu,Mu'omu'a,Neiafu,Niua Fo'ou,Niua Toputapu,Nukunuku,Pangai,Pangaimotu,Tatakamotonga,'Uiha,Vaini");
$states['Trinidad-and-Tobago'] = construct_array("Arima bor,Chaguanas bor,Couva/Tabaquite/Talparo,Diego Martin,Eastern Tobago,Mayaro/Rio Claro,Penal/Debe,Point Fortin bor,Port of Spain cit,Princes Town,San Fernando cit,Sangre Grande,San Juan/Laventille,Siparia,Tunapuna/Piarco,Western Tobago");
$states['Tunisia'] = construct_array("Agareb,Aïn Draham,Akouda,Alaa,El Alia,Amdoun,El Amra,Ariana Médina,Ayoun,Bab Bhar,Bab Souika,Balta Bou Aouane,Bardo,Bargou,El Battan,Béja Nord,Béja Sud,Bekalta,Belkhir,Bembla,Ben Arous,Ben Guerdane,Beni Hassen,Beni Khalled,Beni Khedache,Beni Khiar,Bir Ali Ben Khélifa,Bir El Hfay,Bir Lahmar,Bir Mchergua,Bizerte Nord,Bizerte Sud,Borj El Amri,Bouarada,Bou Argoub,Bouficha,Bouhajla,Boumerdès,Boumhel,Bourouis,Bousalem,Carthage,Chebba,Chebika,Chorbane,Chrarda,Cité El Khadra,Dahmani,Dar Chaabane El Fehri,Degueche,Dhiba,Djerba Ajim,Djerba Houmet Essouk,Djerba Midoun,Douar Hicher,Douz Nord,Douz Sud,Enfidha,Es Sers,Ettadhamen,Ezzahra,Ezzouhour,Fahs,Faouar,Feriana,Fernana,Fouchana,Foussana,Gaafour,Gabès Ouest,Gabès Sud,Gabès Médina,Gafsa Nord,Gafsa Sud,Ghannouch,Ghardimaou,Ghar El Melh,Ghazala,Ghomrassen,El Ghraiba,Goubellat,La Goulette,Grombalia,Guetar,Haffouz,Hajeb El Ayoun,Hamma,Hammam Chott,Hammamet,Hammam Ghezaz,Hammam Lif,Hammam Sousse,Haouaria,Hassi El Ferid,Hazoua,Hbira,Hencha,Hergla,Hidra,Hrairia,Jammel,Jebel Jeloud,Jebeniana,Jedaida,Jedeliane,Jelma,El Jem,Jendouba Nord,Jendouba Sud,Jerissa,Joumine,Kabaria,Kairouan Nord,Kairouan Sud,Kalaa Kebira,Kalaa Khesba,Kalaa Sghira,Kalaat El Andalous,Kalaat Senan,Kasserine Nord,Kasserine Sud,Kebili Nord,Kebili Sud,Kef Est,Kef Ouest,Kelibia,Kerkennah,Kesra,Kondar,Korba,Le Kram,El Krib,Ksar,Ksar Hellal,Ksibet El Mediouni,Ksour,Ksour Essef,Laroussa,M'Hamdia,M'Saken,Mahdia,Mahres,Majel Belabbes,Makthar,Manouba,Mareth,La Marsa,Mateur,Matmata,Matmata Nouvelle,Mazzouna,Mdhilla,Médenine Nord,Médenine Sud,Médina,Mégrine,Mejez El Bab,Meknassi,Melloulech,El Menzah,Menzel Bourguiba,Menzel Bouzaiene,Menzel Bouzelfa,Menzel Chaker,Menzel Habib,Menzel Jemil,Menzel Temime,Metlaoui,Metouia,El Mida,Mnihla,Moknine,Monastir,Mornag,Mornaguia,El Mourouj,Nabeul,Nadhour,Nasrallah,Nebeur,Nefta,Nefza,Nouvelle Médina,Omrane,Omrane Supérieur,El Ouardia,Oued Ellil,Oued Mliz,Ouerdanine,Oueslatia,Ouled Chamekh,Ouled Haffouz,Oum Larais,Radès,Raoued,Ras Jebel,Redeyef,Regueb,Remada,Rouhia,Sabalat Ouled Asker,Sahline,Sakiet Eddaier,Sakiet Ezzit,Sakiet Sidi Youssef,Samar,Saouaf,Sayada-Lamta-Bou Hjar,Sbeitla,Sbiba,Sbikha,Sejnane,Sened,Sfax Médina,Sfax Ouest,Sfax Sud,Sidi Aich,Sidi Ali Ben Aoun,Sidi Alouane,Sidi Bou Ali,Sidi Bouzid Est,Sidi Bouzid Ouest,Sidi El Béchir,Sidi El Heni,Sidi Hassine,Sidi Makhlouf,Sidi Thabet,Sijoumi,Siliana Nord,Siliana Sud,Skhira,Soliman,Souassi,Souk El Ahed,Souk Jedid,Soukra,Sousse Jaouhara,Sousse Médina,Sousse Riadh,Sousse Sidi Abdelhamid,Tabarka,El Tahrir,Tajerouine,Takelsa,Tamaghza,Tataouine Nord,Tataouine Sud,Teboulba,Tebourba,Téboursouk,Testour,Thala,Thibar,Thina,Tinja,Tozeur,Utique,Zaghouan,Zarzis,Zarzouna,Zeramdine,Zriba");
$states['Turkey'] = construct_array("Adana,Adıyaman,Afyonkarahisar,Ağri,Aksaray,Amasya,Ankara,Antalya,Ardahan,Artvin,Aydın,Balıkesir,Bartın,Batman,Bayburt,Bilecik,Bingöl,Bitlis,Bolu,Burdur,Bursa,Çanakkale,Çankırı,Çorum,Denizli,Diyarbakır,Düzce,Edirne,Elazığ,Erzincan,Erzurum,Eskişehir,Gaziantep,Giresun,Gümüşhane,Hakkari,Hatay,Iğdır,Isparta,İstanbul,İzmir,Kahramanmaraş,Karabük,Karaman,Kars,Kastamonu,Kayseri,Kilis,Kırıkkale,Kırklareli,Kırşehir,Kocaeli,Konya,Kütahya,Malatya,Manisa,Mardin,Mersin,Muğla,Muş,Nevşehir,Niğde,Ordu,Osmaniye,Rize,Sakarya,Samsun,Şanlıurfa,Siirt,Sinop,Şırnak,Sivas,Tekirdağ,Tokat,Trabzon,Tunceli,Uşak,Van,Yalova,Yozgat,Zonguldak");
$states['Turkmenistan'] = construct_array("Akdepe,Aşgabat,Babadađhan,Bađramaly - City,Bađramaly,Bäherden,Balkanabat,Bođnyuzyn,Boldumsaz,Büzmeđin,Çärjew - City,Çärjew,Çarşanga,Çeleken,Dänew,Darganata,Daşhowuz - City,Daşhowuz,Đolöten,Đylanly,Esenguly,Farap,Garabekewül,Garagum,Garrygala,Gäwers,Gazanjyk,Gökdepe,Gowurdak,Gubadag,Gumdag,Guşgy,Gyzylarbat,Gyzyletrek,Halaç,Hojambaz,Kaka,Kerki,Köneürgenç,Mary,Murgap,Nyđazow,Sađat,Sakar,Sakarçäge,Saparmyrat Nyđazow,Saparmyrat Türkmenbaşy,Sarahs,Seđdi,Tagta,Tagtabazar,Tejen,Türkmenbaşy,Türkmenbaşy - City,Türkmengala,Wekilbazar");
$states['Turks-and-Caicos-Islands'] = construct_array("Turks and Caicos Islands");
$states['Tuvalu'] = construct_array("Funafuti,Nanumanga,Nanumea,Niutao,Nui,Nukufetau,Nukulaelae,Vaitupu");
$states['Uganda'] = construct_array("Agago,Agule,Ajuri,Amuria,Aringa,Arua,Aruu,Aswa,Ayivu,Bamunanika,Bbale,Bokora,Bubulo,Budadiri,Budaka,Budiope East,Budiope West,Budyebo,Bufumbira,Bugabula,Bugahya,Bugangaizi,Bugangaizi East,Bughendera,Bugweri,Buhaguzi,Buhweju,Buikwe,Bujenje,Bujumba,Bukanga,Bukedea,Bukomansimbi,Bukonzo,Bukooli,Bukooli Island,Bukooli South,Bukoto,Bukoto Central,Bukoto East,Bulambuli,Bulamogi,Buliisa,Bungokho,Bunya,Bunyangabu,Bunyaruguru,Bunyole East,Bunyole West,Burahya,Buruli,Bushenyi-Ishaka,Busia,Busiki,Busiro,Busongora,Busujju,Butambala,Butebo,Butembe,Buvuma Islands,Buwekula,Buyaga,Buyaga West,Buyanja,Buzaaya,Bwamba,Chekwii - Kadam,Chua,Dodoth East,Dodoth West,Dokolo,East Moyo,Entebbe,Erute,Fort Portal,Gomba,Gulu,Hoima,Ibanda,Iganga,Igara,Iki-Iki,Isingiro,Jie,Jinja,Jonam,Kabale,Kaberamaido,Kabula,Kagoma,Kajara,Kakuuto,Kalaki,Kalungu,Kampala,Kapelebyong,Kasambya,Kasese,Kashari,Kasilo,Kassanda,Katerera,Katikamu,Kazo,Kibale,Kibanda,Kiboga East,Kiboga West,Kibuku,Kigulu,Kilak,Kinkinzi,Kioga,Kitagwenda,Koboko,Kole,Kongasis,Kooki,Kumi,Kwania,Kween,Kyadondo,Kyaka,Kyamuswa,Kyotera,Labwor,Lamwo,Lira,Luuka,Lwemiyaga,Madi-Okollo,Manjiya,Maracha,Maruzi,Masaka,Masindi,Matheniko,Mawogola,Mawokota,Mbale,Mbarara,Mityana,Moroto c,Moroto m,Mukono c,Mukono m,Mwenge c,Nakaseke North,Nakaseke South,Nakasongola,Nakifuma,Ndorwa,Ngora,Ntenjeru,Ntoroko,Ntungamo,Nwoya,Nyabushozi,Obongi,Okoro,Omoro,Otuke,Oyam,Padyere,Pallisa,Pian,Rubabo,Rubanda,Ruhaama,Ruhinda,Rujumbura,Rukiga,Rukungiri,Rushenyi,Rwampara,Samia Bugwe,Serere c,Sheema c,Soroti c,Soroti m,Terego c,Tingey c,Toroma c,Tororo c,Tororo m,Upe c,Usuk c,Vurra c,West Budama,West Moyo");
$states['Ukraine'] = construct_array("Cherkasy region,Chernihiv region,Chernivtsi regios,Republic of Crimea,Dnipropetrovs'k region,Donets'k region,Ivano-Frankivs'k region,Kharkiv region,Kherson region,Khmel'nyts'kyy region,Kiev region,Kiev City,Kirovohrad region,Luhans'k region,L'viv region,Mykolayiv region,Odessa region,Poltava region,Rivne region,Sevastopol' City,Sumy region,Ternopil' region,Transcarpathia region,Vinnytsya region,Volyn region,Zaporizhzhya region,Zhytomyr region");
$states['United-Arab-Emirates'] = construct_array("Abu Dhabi,Ajman,Dubay,Fujayrah,Ras al Khaymah,Sharjah,Umm al Qaywayn");
$states['United-Kingdom'] = construct_array("Aberdeen,Aberdeenshire,Anglesey,Angus,Antrim,Ards,Argyll and Bute,Armagh,Ballymena,Ballymoney,Bambridge,Barnsley,Bath and North East Somerset,Bedford,Belfast,Birmingham,Blackburn with Darwen,Blackpool,Blaenau Gwent,Bolton,Bourmemouth,Bracknell Forest,Bradford,Bridgend,Brighton and Hove,Bristol,Buckinghamshire,Bury,Caerphilly,Calderdale,Cambridgeshire,Cardiff,Carmarthenshire,Carrickfergus,Castlereah,Central Bedfordshire,Ceredigion,Cheshire East,Cheshire West and Chester,Clackmannanshire,Coleraine,Conwy,Cookstown,COmwall,Conventry,Craigavon,Cumbria,Darlington,Denbighshire,Derby,Derbyshire,Derry,Devon,Doncaster,Dorset,Down,Dudley,Dumfries and Galloway,Dundee,Dungannon,Durham,East Ayrshire,East Dunbartonshire,East Lothian,East Renfrewshire,East Riding of Yorkshire,East Sussex,Edinburgh,Eilean Siar,Essex,Falkirk,Fermanagh,Fife,Flintshire,Gateshead,Glasgow,Gloucestershire,Greater London,Gwynedd,Halton,Hampshire,Hartlepool,Herefordshire,Hertfordshire,Highland,Inverclyde,Isle of Wight,Isles of Scilly,Kent,Kingston upon Hull,Kirklees,Knowsley,Lancashire,Larne,Leeds,Leicester,Leicestershire,Limavady,Lincolnshire,Lisburn,Liverpool,Luton,Magherafelt,Manchester,Medway,Merthyr Tydfil,Middlesbrough,Midlothian,Milton Keynes,Monmouthshire,Moray,Moyle,Neath Port Talbot,Newcastle upon Tyne,Newport,Newry and Mourne,Newtownabbey,Norfolk,Northamptonshire,North Ayrshire,North Down,North East Licolnshire,North Lanarkshire,North Lincolnshire,North Somerset,North Tyneside,Northumberland,North Yorkshire,Nottingham,Nottinghamshire,Oldham,Omagh,Orkney Islands,Oxfordshire,Pembrokeshire,Perthshire and Kinross,Peterborough,Plymouth,Poole,Portsmouth,Powys,Reading,Redcar and Cleveland,Renfrewshire,Rhondda Cynon Taff,Rochdale,Rotherham,Rutland,Saint Helens,Salford,Sandwell,Scottish Borders,Sefton,Sheffield,Shetland Islands,Shropshire,Slough,Solihull,Somerset,Southampton,South Ayrshire,Southend-on-Sea,South Gloucestershire,South Lanarkshire,South Tyneside,Staffordshire,Stirling,Stockport,Stockton-on-Tees,Stoke-on-Trent,Strabane,Suffolk,Sunderland,Surrey,Swansea,Swindon,Tameside,Telford and Wrekin,Thurrock,Torbay,Torfaen,Trafford,Vale of Glamorgan,Wakefield,Walsall,Warrington,Warwickshire,West Berkshire,West Dunbartonshire,West Lothian,West Sussex,Wigan,Wiltshire,Windsor and Maidenhead,Wirral,Wokingham,Wolverchampton,Worcestershire,Wrexham,York");
$states['USA'] = construct_array("Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,Florida,Georgia,Hawaii,Idaho,Illinois,Indiana,Iowa,Kansas,Kentucky,Louisiana,Maine,Maryland,Massachusetts,Michigan,Minnesota,Mississippi,Missouri,Montana,Nebraska,Nevada,New Hampshire,New Jersey,New Mexico,New York,North Carolina,North Dakota,Ohio,Oklahoma,Oregon,Pennsylvania,Rhode Island,South Carolina,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming");
//$states['United-States-Minor-Outlying-Islands'] = construct_array("Baker Island,Howland Island,Jarvis Island,Johnston Atoll,Kingman Reef,Midway Islands,Navassa Island,Palmyra Atoll,Wake Island");
$states['Uruguay'] = construct_array("Artigas,Canelones,Cerro Largo,Colonia,Durazno,Flores,Florida,Lavalleja,Maldonado,Montevideo,Paysandú,Río Negro,Rivera,Rocha,Salto,San José,Soriano,Tacuarembó,Treinta");
$states['Uzbekistan'] = construct_array("Akmal Ikromov,Amudaryo,Andijon,Andijon - Kuyganyor Angor,Angren,Arnasoy,Asaka,Asaka - Asaka,Bahoriston,Baliqchi,Bandixon,Baxmal,Baxt,Bekobod,Bekobod - Zafar,Bektemir,Beruniy,Beruniy - Beruniy,Beshariq,Bog'dod,Bog'ot,Bo'ka,Bo'stonliq,Boyovut,Boysun,Bo'zatov,Bo'zsuv,Buloqboshi,Bulung'ur,Buvayda,Buxoro,Buxoro - Galaosiyo,Chilonzor,Chimboy,Chinoz,Chirchiq,Chiroqchi,Chortoq,Chortoq - Chortoq,Chust,Dang'ara,Dashtobod,Dehqonobod,Denov,Do'stlik,Ellikqala,Farg'ona,Farg'ona - Vodil,Forish,Furqat,G'allaorol,G'ijduvon,Guliston,Guliston - Dehqonobod,Gurlan,G'uzor,Hamza,Haqqulobod,Hazorasp,Ishtixon,Izboskan,Jalolquduq,Jarqo'rg'on,Jizzax,Jizzax - Uchtepa,Jomboy,Jondor,Kasbi,Kattaqo'rg'on,Kattaqo'rg'on - Payshanba,Kegeyli,Kitob,Kogon,Kogon,Konimex,Koson,Kosonsoy,Marg'ilon,Marhamat,Mehnatobod,Mingbuloq,Mirobod,Mirzacho'l,Mirzaobod,Mirzo Ulug'bek,Mo'ynoq,Muborak,Muzrabot,Namangan,Namangan - Toshbuloq,Narpay,Navbahor,Navoiy,Nishon,Norin,Nukus,Nukus - Oqmang'it,Nurobod,Nurota,Ohangaron,Olmaliq,Olot,Oltiariq,Oltinko'l,Oltinsoy,Oqaryo,Oqoltin,Oqqo'rg'on,Oqtosh,O'rtachirchiq,Oxunboboev,O'zbekiston,Parkent,Pastdarg,Paxtachi,Paxtakor,Paxtaobod,Payariq,Peshku,Piskent,Pitnak,Pop,Qamashi,Qanliko'l,Qarshi,Qarshi - Beshkent,Qibray,Qiziltepa,Qiziriq,Qo'ng'irot,Qo'qon,Qorako'l,Qorao'zak,Qorasuv,Qo'rg'ontepa,Qorovulbozor,Qo'shko'pir,Qo'shrabot,Qumqo'rg'on,Quva,Quvasoy,Quyichirchiq,Rishton,Romitan,Samarqand,Samarqand - Gulobod,Sariosiyo,Sayxunobod,Sergeli,Shahrisabz,Shahrixon,Sharof Rashidov,Shayxontohur,Sherobod,Shirin,Shofirkon,Sho'rchi,Shovot,Shumanay,Sirdaryo,Sobir Rahimov,So'x,Taxiatosh,Taxtako'pir,Termiz,Tomdi,To'raqo'rg'on,To'rtko'l,Toshkent,Toshloq,Toyloq,Uchko'prik,Uchqo'rg'on,Uchquduq,Ulug'nor,Urganch,Urganch - Qorovul,Urgut,Usmon Yusupov,Uychi,Uzun,Vobkent,Xatirchi,Xiva,Xo'jaobod,Xo'jayli,Xonobod,Xonqa,Xovos,Yagiqo'rg'on,Yakkabog',Yakkasaroy,Yangiariq,Yangibozor,Yangiobod,Yangiobod - Balandchaqir,Yangiyer,Yangiyo'lYangiyo'l - Gulbahor,Yozyovon,Yunusobod,Yuqorichirchiq,Zafarobod,Zangiota,Zarafshon,Zarbdor,Zomin");
$states['Vanuatu'] = construct_array("Aneityum,Aniwa,Bangan-Vanua,Canal-Fanafo,Central Malekula,Central Pentecost 1,Central Pentecost 2,Central Torba,East Malo,East Santo,Emau,Erakor,Eratap,Eton,Futuna,Ifira,Luganville,Lungei-Tagaro,Makimae,Malorua,Mele,Middle Bush Tanna,Nguna,North Ambae,North Ambrym,North East Malekula,North Efate,North Erromango,North Pentecost,North Santo,North Tanna,North Tongoa,North West Malekula,North West Santo,Northern Torba,Paama,Pango,Port Vila,South Ambae,South East Ambrym,South East Malekula,South East Santo,South Erromango,South Maewo,South Malekula,South Pentecost,South Santo,South Tanna,South West Malekula,South West Tanna,Southern Torba,Tongariki,Varisu,Vermali - Ringdove,Vermaul,West Ambae,West Ambrym,West Malo,West Santo,West Tanna,Whitesands Tanna,Yarsu,Aneityum,Aniwa,Big Bay,Buninga,Central Malakula,Central Pentecost,Central Tongoa,East Aoba,East Efate,East Epi,East Erromango,East Malakula,East Santo,East Tanna,Emae,Emao,Erakor,Fanafo-Canal,Futuna,Gaua- Merig,Ifira,Luganville,Makira,Mataso,Mele,Mere Lava,Mota,Mota Lava,Nguma-Pele,North Ambrym,North Aoba,North East Malakula,North Efate,North Epi,North Maewo,North Malo,North Paama,North Pentecost,North Tanna,North Tongoa,North West Malakula,North West Santo,Pango,Port Vila,South Aoba,South East Ambrym,South East Malakula,South East Santo,South Efate,South Epi,South Maewo,South Malo,South Paama,South Pentecost,South Santo,South Tanna,South Tongoa,South West Malakula,Tongariki,Torres,Uraparapara,Vanua Lava,West Ambrym,West Aoba,West Epi,West Erromango,West Santo,West Tanna");
$states['Vatican City'] = construct_array("Vatican City");
$states['Venezuela'] = construct_array("Acevedo,Achaguas,Acosta,Acosta,Agua Blanca,Aguasay,Alberto Adriani,Alberto Arvelo Torrealba,Almirante Padilla,Alto Orinoco,Anaco,Andrés Bello - La Azulita,Andrés Bello - San José de Barlovento,Andrés Bello - Cordero,Andrés Bello - Santa Isabel,Andrés Eloy Blanco - El Cantón,Andrés Eloy Blanco - Sanare,Andrés Eloy Blanco - Casanay,Andrés Mata,Antolín del Campo,Antonio Díaz,Antonio José de Sucre,Antonio Pinto Salinas,Antonio Rómulo Costa,Anzoátegui,Aragua,Araure,Aricagua,Arismendi - Arismendi,Arismendi - La Asunción,Arismendi - Río Caribe,Arístides Bastidas - San Pablo,Arzobispo Chacón,Atabapo,Atures,Autana,Ayacucho,Baralt,Barinas,Baruta,Bejuma,Benítez,Bermúdez,Biruaca,Boconó,Bolívar - San Mateo,Bolívar - Barinitas,Bolívar - San Luís,Bolívar - Caripito,Bolívar - Mariguitar Bolívar - San Antonio del Táchira,Bolívar - Sabana Grande,Bolívar - Aroa,Brión,Bruzual,Buchivacoa,Buroz,Cabimas,Cacique Manaure,Cajigal,Camaguán,Camatagua,Campo Elías,Candelaria,Caracciolo Parra Olmedo,Carache,
Cardenal Quintero,Cárdenas,Caripe,Carirubana,Carlos Arvelo,Caroní,Carrizal,Casacoima,Catatumbo,Cedeño - Caicara del Orinoco,Cedeño - Caicara,Chacao,Chaguaramas,Cocorote,Colina,Colón,Córdoba,Crespo,Cristóbal Rojas,Cruz Paredes,Cruz Salmerón Acosta,Dabajuro,Democracia,Dependencias Federales,Díaz,Diego Bautista Urbaneja,Diego Ibarra,El Callao,El Hatillo,El Socorro,Escuque,Esteller,Ezequiel Zamora - Santa Bárbara,Ezequiel Zamora - Punta de Mata,Falcón - Tinaquillo,Falcón - Pueblo Nuevo,Federación,Fernández Feo,Fernando de Peñalver,Francisco del Carmen Carvajal,Francisco de Miranda - Pariaguán,Francisco de Miranda - Calabozo,Francisco de Miranda - San José de Bolívar,Francisco Javier Pulgar,Francisco Linares Alcántara,García,García de Hevia,Girardot - Maracay,Girardot - El Baúl,Gómez,Gran Sabana,Guacara,Guaicaipuro,Guanare,Guanarito,Guanta,Guaraque,Guasimos,Heres,Independencia - Soledad,Independencia - Santa Teresa del Tuy,Independencia - Capacho Nuevo,Independencia - Independencia,Iribarren,Jacura,Jauregui,
Jesús Enrique Lossada,Jesús María Semprún,Jiménez,José Angel Lamas,José Antonio Páez,José Felipe Márquez Cañizales,José Félix Ribas - La Victoria,José Félix Ribas - Tucupido,José Gregorio Monagas,José María Vargas,José Rafael Revenga,José Tadeo Monagas,Juan Antonio Sotillo,Juan Germán Roscio,Juan José Mora,Juan Manuel Cajigal,Juan Vicente Campo Elías,Julián Mellado,Julio César Salas,Junín,Justo Briceño,La Cañada de Urdaneta,La Ceiba,Lagunillas,Lander,Las Mercedes,La Trinidad,Leonardo Infante,Libertad - San Mateo,Libertad - Capacho Viejo,Libertador - Palo Negro,Libertador - Tocuyito,Libertador - Caracas,Libertador - Mérida,Libertador - Temblador,Libertador - Tunapuy,Libertador - Abejales,Lima Blanco - Macapo,Lobatera,Los Guayos,Los Salias,Los Taques,Machiques de Perijá,Manapiare,Maneiro,Manuel Ezequiel Bruzual,Manuel Monge,Mara,Maracaibo,Marcano,Mariño - Porlamar,Mariño - Irapa,Mario Briceño Iragorry,Maroa,Maturín,Mauroa,Mejía,Michelena,Miranda - Miranda,Miranda - Santa Ana de Coro,Miranda - Timotes,
Miranda -  Dividive,Miranda - Los Puertos de Altagracia,Monseñor Iturriza,Monseñor José Vicente de Unda,Montalbán,Monte Carmelo,Montes,Morán,Motatán,Muñoz,Naguanagua,Nirgua,Obispo Ramos de Lora,Obispos,Ocumare de la Costa de Oro,Ortíz,Ospino,Padre Noguera,Padre Pedro Chien,Páez - Guasdualito,Páez - Río Chico,Páez - Acarigua,Páez - Sinamaica, Palavecino,Palmasola,Pampán,Pampanito,Panamericano,Pao de San Juan Bautista,Papelón,Paz Castillo,Pedernales,Pedraza,Pedro Camejo,Pedro Gual,Pedro María Freites,Pedro María Ureña,Pedro Zaraza,Peña,Península de Macanao,Petit,Piar - Upata,Piar - Aragua,Píritu - Píritu,Plaza,Pueblo Llano,Puerto Cabello,Punceres,Rafael Rangel,Rafael Urdaneta,Rangel,Raúl Leoni,Ribero,Ricaurte,Río Negro,Rivas Dávila,Rojas,Rómulo Gallegos - Elorza,Rómulo Gallegos - Las Vegas,Rosario de Perijá,Roscio,Samuel Darío Maldonado,San Carlos,San Casimiro,San Cristóbal,San Diego,San Felipe,San Fernando,San Francisco - Mirimire,San Francisco,San Genaro de Boconoito,San Gerónimo de Guayabal,San Joaquín,
San José de Guanipa - San José de Guanipa,San José de Guaribe - San José de Guaribe,San Juan de Capistrano - Boca de Uchire,San Judas Tadeo,San Rafael de Carvajal,San Rafael de Onoto,San Sebastián,Santa Ana,Santa Bárbara,Santa María de Ipire,Santa Rita,Santa Rosalía,Santiago Mariño,Santos Marquina,Santos Michelena,Seboruco,Sifontes,Silva,Simón Bolívar - Barcelona,Simón Bolívar - San Francisco de Yare,Simón Bolívar - Tía Juana,Simón Planas,Simón Rodríguez - El Tigre,Simón Rodríguez - San Simón,Sir Artur McGregor,Sosa,Sotillo,Sucre - Cagua,Sucre - Maripa,Sucre - La Cruz de Taratara,Sucre - Lagunillas,Sucre - Petare,Sucre - Biscucuy,Sucre - Cumaná,Sucre - Queniquea,Sucre - Sabana de Mendoza,Sucre - Guama,Sucre - Bobures,Tinaco,Tocopero,Torbes,Torres,Tovar - Colonia Tovar,Tovar, Trujillo,Tubores,Tucupita,Tulio Febres Cordero,Turén,Unión,Urachiche,Uracoa,Urdaneta - Barbacoas,Urdaneta - Siquisique,Urdaneta - Cúa,Urdaneta - La Quebrada,Uribante,Urumaco,Valdez,Valencia,Valera,Valmore Rodríguez,Vargas,Veroes,Villalba,
Zamora - Villa de Cura,Zamora - Puerto Cumarebo,Zamora - Guatire,Zea");
$states['Vietnam'] = construct_array("A Luoi,An Bien,An Duong,Anh Son,An Khe,An Trung - An Lao,An Lao,An Minh,An Nhon,An Phu,An Thi,Ayun Pa,Ba Be,Bac Ai,Bac Binh,Bac Giang,Bac Ha,Ba Che,Bach Long,Bach Thong,Bac Kan,Bac Lieu,Bac Me,Bac Ninh,Bac Quang,Bac Son,Bac Tra My,Bac Yen,Ba Dinh,Bao Lac,Bao Lam,Loc Thang,Bao Loc,Bao Thang,Bao Yen,Ba Ria,Ba Thuoc,Ba To,Ba Tri,Bat Xat,Ba Vi,Ben Cat,Ben Cau,Ben Luc,Ben Tre,Bien Hoa,Bim Son,inh Chanh,Binh Dai,Binh Gia,inh Giang,Binh Lieu,Binh Long,Binh Luc,Binh Minh,Binh Son,Binh Tan,Binh Thanh,Binh Thuy,Binh Xuyen,Bo Trach,Bu Dang,Bu Dop,Buon Don,Buon Ma Thuot,Cai Be,Cai Lay,Cai Nuoc,Cai Rang,Ca Mau,Cam Giang,Cam Khe,Cam Le,Cam Lo,Cam My,Cam Pha,Cam Ranh,Cam Thuy,Cam Xuyen,Can Duoc,Can Gio,Can Giuoc,Cang Long,Can Loc,Cao Bang,Cao Lanh,Cao Lanh,Cao Loc,Cao Phong,Cat Hai,Cat Tien,Cau Giay,Cau Ke,Cau Ngang,Chau Doc,Chau Duc,Chau Phu,Chau Thanh - An Chau,Chau Thanh - Chau Thanh,Chau Thanh - Cai Tau Ha, Chau Thanh - Nga Sau,Chau Thanh - Minh Luong,Chau Thanh - Tam Vu,Chau Thanh - Tan Hiep,Chau Thanh - Chau Thanh,
Chau Thanh A - Mot Ngan,Chiem Hoa - Vinh Loc,Chi Lang - Dong Mo,Chi Linh - Sao Do,Cho Don,Cho Gao,Cho Lach,Cho Moi,Chon Thanh,Chuong My,Chu Pah,Chu Prong,Chu Se,Co Do,Con Co,Con Cuong,Con Dao,Co To,Cua Lo,Cu Chi,Cu Jut,Cu Lao Dung,Cu M'Gar,Da Huoai,Dai Loc,Dai Tu,Dak Doa,Dak Glei,Dak Ha,Dak Mil,Dak Nong,Dak Po,Dak Rlap,Dakrong,Dak Song,Dak To,Da Lat,Dam Doi,Dam Ha,Dam Rong,Dan Phuong,Da Rac,Dat Do,Da Teh,Dau Tieng,Di An,Dien Ban,Dien Bien - Muong Thanh,Dien Bien Dong,Dien Bien Phu,Dien Chau,Dien Khanh,Di Linh,Dinh Hoa,Dinh Lap,Dinh Quan,Doan Hung,Do Luong,Don Duong,Dong Anh,Dong Da,Dong Giang,Dong Ha,Dong Hai - Ganh Hao,Dong Hoi - Dong Hoi,Dong Hung,Dong Hy,Dong Phu,Dong Son,Dong Trieu,Dong Van,Dong Xoai,Dong Xuan,Do Son,Duc Co,Duc Hoa,Duc Hue,Duc Linh,Duc Pho,Duc Tho,Duc Trong,Duong Minh Chau,Duyen Hai,Duy Tien,Duy Xuyen,Ea H'Leo,Ea Kar,Ea Sup,Gia Binh,Gia Lam,Gia Loc,Giao Thuy,Gia Rai,Gia Vien,Gio Linh,Giong Rieng,Giong Trom,Go Cong - Go Cong,Go Cong Dong - Tan Hoa,Go Cong Tay - Vinh Binh,Go Dau,Go Quao,
Go Vap,Ha Dong,Ha Giang,Ha Hoa,Hai An,Hai Ba Trung,Hai Chau,Hai Duong,Hai Ha,Hai Hau,Hai Lang,Ha Lang,Ha Long,Ham Tan,Ham Thuan Bac,Ham Thuan Nam,Ham Yen,Ha Quang,Ha Tien,Ha Tinh,Ha Trung,Hau Loc,Hiep Duc,Hiep Hoa,Hoa An,Goa Binh,Hoai An,Hoai Duc,Hoai Nhon,Hoa Lu,Hoang Hoa,Hoang Mai,Hoang Sa,Hoang Su Phi,Hoanh Bo,Hoan Kiem,Hoa Thanh,Hoa Vang,Hoc Mon,Hoi An,Hon Dat,Hong Bang,Hong Dan,Hong Linh,Hong Ngu,Hue,Hung,Hung Nguyen,Hung Yen,Huong Hoa,Huong Khe,Huong Son,Huong Thuy,Huong Tra,Huu Lung,Ia Grai,Ia Pa,Kbang,Ke Sach,Khanh Son,Khanh Vinh,Khoai Chau,Kien An,Kien Hai,Kien Luong,Kien Thuy,Kien Xuong,Kim Bang,Kim Boi,Kim Dong,Kim Son,Kim Thanh,Kinh Mon,Kong Chro,Kon Plong,Kon Ray,Kon Tum,Krong Ana,Krong Bong,Krong Buk,Krong Nang,Krong No,Krong Pa,Krong Pak,Ky Anh,Ky Son - Ky Son,Ky Son - Muong Xen,Lac Duong,Lac Son,Lac Thuy,Lai Chau,Lai Vung,Lak,Lam Ha,Lam Thao,Lang Chanh,Lang Giang,Lang Son,Lao Cai,Lap Thach,Lap Vo,Le Chan,Le Thuy,Lien Chieu,Loc Binh,Loc Ninh,Long Bien,Long Dien,Long Ho,Long Khanh,
Long My - Long My,Long My - Soc Trang,Long Phu,Long Thanh,Long Xuyen,Luc Nam,Luc Ngan,Luc Yen,Luong Son,Luong Tai,Ly Nhan,Ly Son,Mai Chau,Mai Son,Mang Thit,Mang Yang,M'Drak,Me Linh,Meo Vac,Minh Hoa,Minh Long,Mo Cay,Moc Chau,Moc Hoa,Mo Duc,Mong Cai,Mu Cang Trai,Muong Cha,Muong Khuong,Muong La,Muong Lat,Muong Lay,Muong Nhe,Muong Te,My Duc,My Hao,My Loc,My Tho,My Tu,My Xuyen,Na Hang,Nam Can,Nam Dan,Nam Dinh,Nam Dong,Nam Giang,Nam Sach,Nam Tra My,Nam Truc,Na Ri,Nga Nam,Ngan Son,Nga Son,Nghia Dan,Nghia Hanh,Nghia Hung,Nghia Lo,Nghi Loc,Nghi Xuan,Ngoc Hien,Ngoc Hoi,Ngoc Lac,Ngo Quyen,Ngu Hanh Son,Nguyen Binh,Nha Be,Nha Trang,Nhon Trach,Nho Quan,Nhu Thanh,Nhu Xuan,Ninh Binh,Ninh Giang,Ninh Hai,Ninh Hoa,Ninh Kieu,Ninh Phuoc,Ninh Son,Nong Cong,Nui Thanh,O Mon,Pac Nam,Phan Rang-Thap Cham,Phan Thiet,Phong Dien - My Khanh,Phong Dien - Phong Dien,Phong Tho,Pho Yen,Phu Binh,Phu Cat,Phuc Hoa,Phuc Tho,Phu Cu,Phuc Yen,Phu Giao,Phu Hoa,Phu Loc,Phu Luong,Phu Ly,Phu My,Phung Hiep,Phu Nhuan,Phu Ninh - Phong Chau,
Phu Ninh - Tam Da,Phuoc Long - Phuoc Long,Phuoc Long - Thac Mo,Phuoc Son,Phu Quoc,Phu Quy,Phu Tan - Cho Vam,Phu Tan - Cai Doi Vam,Phu Tho,Phu Vang,Phu Xuyen,Phu Yen,Pleiku,Quan 1,Quan 2,Quan 3,Quan 4,Quan 5,Quan 6,Quan 7,Quan 8,Quan 9,Quan 10,Quan 11,Quan 12,Quan Ba,Quang Binh,Quang Dien,Quang Ngai,Quang Ninh,Quang Trach,Quang Tri,Quang Xuong,Quang Yen,Quan Hoa,Quan Son,Que Phong,Que Son,Que Vo,Quoc Oai,Quy Chau,Quy Hop,Quynh Luu,Quynh Nhai,Quy Nhon,Quynh Phu,Rach Gia,Sa Dec,Sam Son,Sa Pa,Sa Thay,Si Ma Cai,Sin Ho,Soc Son,Son Dong,Son Duong,Song Cau,Song Cong,Song Hinh,Song Ma - Song Ma,Son Ha - Di Lang,Son Hoa,Son La,Son Tay - Son Dung,Son Tay - Son Tay,Son Tinh,Son Tra,Sop Cop,Tam Binh,Tam Dao,Tam Diep,Tam Duong - Tam Duong,Tam Duong - Hop Hoa,Tam Ki,Tam Nong - Tram Chim,Tam Nong - Hung Hoa,Tan An,Tan Bien,Tan Binh,Tan Chau - Tan Chau,Tan Hiep,Tanh Linh,Tan Hong - Sa Rai,Tan Hung - Tan Hung,Tan Ky,Tan Lac,Tan Phu - Tan Phu,Tan Phu - Ho Chi Minh City,Tan Phuoc,Tan Thanh - Phu My,Tan Thanh - Tan Thanh,Tan Tru,Tan Uyen,Tan Yen,Tay Giang,Tay Ho,Tay Ninh,Tay Son,Tay Tra,Thach An,Thach Ha,Thach Thanh,Thach That,Thai Binh,Thai Nguyen,Thai Thuy,Thang Binh,Thanh Ba,Thanh Binh,Thanh Chuong,Thanh Ha,Thanh Hoa,Thanh Khe,Thanh Liem,Thanh Mien,Thanh Oai,Thanh Phu,Thanh Son,Thanh Thuy,Thanh Tri - Van Dien,Thanh Tri - Phu Loc,Thanh Xuan,Than Uyen,Thap Muoi,Thieu Hoa,Thoai Son,Thoi Binh,Thong Nhat,Thong Nong,Thot Not,Tho Xuan,Thuan An,Thuan Chau,Thuan Thanh,Thu Dau Mot,Thu Duc,Thuong Tin,Thuong Xua,Thu Thua,Thuy Nguyen,Tien Du,Tien Hai,Tien Lang,Tien Lu,Tien Phuoc,Tien Yen,Tieu Can,Tinh Bien,Tinh Gia,Tra Bong,Tra Cu,Tra Linh,Tram Tau,Trang Bang,Trang Bom,Trang Dinh,Tran Van Thoi,Tran Yen,Tra On,Tra Vinh,Trieu Phong,Trieu Son,Tri Ton,Truc Ninh,Trung Khanh,Truong Sa,Tua Chua,Tuan Giao,Tu Ky,Tu Liem,Tu Nghia,Tuong Duong,Tu Son,Tuy An,Tuyen Hoa,Tuyen Quang,Tuy Hoa,Tuy Hoa,Tuy Phong,Tuy Phuoc,U Minh,Ung Hoa,Uong Bi,Van Ban,Van Canh,Van Chan,Van Don,Van Giang,Van Lam,Van Lang,Van Ninh,Van Quan,Van Yen,Viet Tri,Viet Yen,Vinh,Vinh Bao,
Vinh Chau,Vinh Cuu,Vinh Hung,Vinh Linh,Vinh Loc,Vinh Loi,Vinh Long,Vinh Thanh - Vinh Hao,Vinh Thanh - Thanh An,Vinh Thuan,Vinh Tuong,Vinh Yen,Vi Thanh,Vi Thuy,Vi Xuyen,Vo Nhai,Vu Ban,Vung Liem,Vung Tau,Vu Quang,Vu Thu,Xin Man,Xuan Loc,Xuan Truon,Xuyen Moc,Yen Bai,Yen Chau,Yen Dinh,Yen Dung,Yen Hung,Yen Khanh,Yen Lac,Yen Lap,Yen Minh,Yen Mo,Yen My,Yen Phong,Yen Son,Yen Than,Yen The,Yen Thuy,Y Yen");
$states['Virgin-Islands'] = construct_array("Anna's Hope Village,Central,Charlotte Amalie,Christiansted,Coral Bay,Cruz Bay,East End,Frederiksted,Northcentral,Northside,Northwest,Sion Farm,Southcentral,Southside,Southwest,Tutu,Water Island,West End,Virgin-Islands-(British)");
$states['Wallis-and-Futuna'] = construct_array("Alo,Hahake,Hihifo,Mua,Singave");
//$states['Western-Sahara'] = construct_array("Western-Sahara");
//Short Yemen version $states['Yemen'] = construct_array("Sanaa,Taizz,Al Hudaydah,Aden,Ibb,Dhamar,al-Mukalla,Zinjibar,Sayyan,Ash Shihr,Sahar,Zabid,Hajjah,Badschil,Dhi as-Sufal,Rida,Socotra,Bait al-Faqih,al-Marawi'a,Al Bayda',Lahij,Marib,Mocha");
$states['Yemen'] = construct_array("Abs,Ad Dahi,Ad Dhale'e,Ad Dis,Ad Durayhimi,Adh Dhlia'ah,Aflah Al Yaman,Aflah Ash Shawm,Ahwar,Ain,Al Abdiyah,Al Abr,Al A'rsh,Al Ashah,Al Azariq,Al Bayda,Al Bayda City,Al Buraiqeh,Al Dhaher,Al Dhihar,Al Garrahi,Al Ghaydah,Al Ghayl,Al Had,Al Hada,Al Hajjaylah,Al Hali,Al Hashwah,Al Hawak,Al Hawtah,Al Haymah Ad Dakhiliyah,Al Haymah Al Kharijiyah,Al Hazm,Al Humaydat,Al Husha,Al Husn,Al Hussein,Al Jabin,Al Jafariyah,Al Jamimah,Al Jubah,Al Khabt,Al Khalq,Al Khawkhah,Alluheyah,Al Ma'afer,Al Madan,Al Madaribah Wa Al Arah,Al Maflahy,Al Maghrabah,Al Mahabishah,Al Mahfad,Al Mahwait,Al Mahwait City,Al Makhadir,Al Malagim,Al Manar,Al Mansura,Al Mansuriyah,Al Maqatirah,Al Marawi'ah,Al Mashannah,Al Masilah,Al Maslub,Al Matammah,Al Maton,Al Mawasit,Al Miftah,Al Mighlaf,Al Milah,Al Mina,Al Misrakh,Al Mualla,Al Mudhaffar,Al Mukalla,Al Mukalla City,Al Mukha,Al Munirah,Al Musaymir,Al Qabbaytah,Al Qaf,Al Qaflah,Al Qafr,Al Qahirah,Al Qanawis,Al Qatn,Al Quraishyah,Al Talh,Al Udayn,Al Wade'a,Al Wahd,Al Wazi'iyah,Amd,Amran,An Nadirah,Anss,Arhab,Arma,Ar Radmah,Ar Rawdah,Ar Raydah Wa Qusayar,Ar Rujum,Ar Ryashyyah,Ash Shaghadirah,Ash Shahil,Ash Shaikh Outhman,Ash Sha'ir,Ash Shamayatayn,Ash Sharyah,Ash Shihr,Ash Shu'ayb,Aslem,As Sabain,As Sabrah,As Saddah,Assafi'yah,As Safra,As Said,As Salafiyah,As Salif,As Sawadiyah,As Sawd,As Sawm,As Sawma'ah,As Sayyani,As Silw,As Sudah,As Sukhnah,Ataq,Ath'thaorah,At Taffah,At Tahrir,At Ta'iziyah,Attawahi,At Tawilah,At Tuhayat,Attyal,Az Zahir,Az'zal,Az Zaydiyah,Az Zuhrah,Ba'dan,Bajil,Bakil Al Mir,Bani Al Awam,Bani Al Harith,Bani Dhabyan,Bani Hushaysh,Bani Matar,Bani Qa'is,Bani Sa'd,Bani Suraim,Baqim,Bart Al Anan,Bayhan,Bayt Al Faqiah,Bidbadah,Bilad Ar Rus,Bilad At Ta'am,Brom Mayfa,Bura,Craiter,Damt,Dar Sad,Daw'an,Dawran Aness,Dhamar City,Dhar,Dhi As Sufal,Dhi Bin,Dhi Na'im,Dhubab,Dimnat Khadir,Far Al Udayn,Ghamr,Ghayl Ba Wazir,Ghayl Bin Yamin,Habban,Habil Jabr,Habur Zulaymah,Hagr As Sai'ar,Hajjah,Hajjah City,Hajr,Halimayn,Hamdan,Harad,Harf Sufyan,Harib,Harib Al Qaramish,
HaHatib,Hawf,Haydan,Hayfan,Hayran,Hays,Hazm Al Udayn,Hidaybu,Hubaysh,Hufash,Huraidhah,Huswain,Huth,Ibb,Iyal Surayh,Jabal Ash Sharq,Jabal Habashy,Jabal Iyal Yazid,Jabal Murad,Jabal Ra's,Jahaf,Jahran,Jardan,Jayshan,Jiblah,Jihanah,Juban,Kamaran,Khabb wa ash Sha'af,Khamir,Khanfir,Kharab Al Marashi,Kharif,Khayran Al Muharraq,Khur Maksar,Khwlan,Kitaf wa Al Boqe'e,Ku'aydinah,Kuhlan Affar,Kuhlan Ash Sharaf,Kushar,Kusmah,Lawdar,Ma'ain,Mabyan,Maghirib Ans,Mahliyah,Majz,Majzar,Manakhah,Man'ar,Maqbanah,Marib,Marib City,Mashra'a Wa Hadnan,Maswar,Maswarah,Mawiyah,Mawza,Mayfa'a,Mayfa'at Anss,Mazhar,Medghal,Merkhah Al Ulya,Merkhah As Sufla,Midi,Milhan,Monabbih,Mudhaykhirah,Mudiyah,Mukayras,Mustaba,Najrah,Na'man,Nati',Nihm,Nisab,Old City,Qa'atabah,Qafl Shamer,Qarah,Qatabir,Qishn,Qulensya Wa Abd Al Kuri,Rada',Radfan,Radman Al Awad,Raghwan,Rahabah,Rajuzah,Rakhyah,Rasad,Raydah,Razih,Rudum,Rumah,Sa'adah,Sabah,Sabir Al Mawadim,Sa'fan,Sah,Sahar,Salh,Sama,Sanhan,Saqayn,Sarar,Sayhut,Sayun,Shada'a,Shahan,Shaharah,Shara'b Ar Rawnah,
Shab As Salam,Sharas,Shibam,Shibam Kawkaban,Shu'aub,Sibah,Sirwah,Suwayr,Tarim,Thamud,Thula,Tuban,Tur Al Bahah,Usaylan,Utmah,Wadhrah,Wadi Al Ayn,Wald Rabi',Washhah,Wusab Al Ali,Wusab As Safil,Yabuth,Yafa'a,Yahr,Yarim,Zabid,Zamakh wa Manwakh,Zingibar");
$states['Zambia'] = construct_array("Chadiza,Chama,Chavuma,Chibombo,Chiengi,Chililabombwe,Chilubi,Chingola,Chinsali,Chipata,Choma,Chongwe,Gwembe,Isoka,Itezhi Tezhi,Kabompo,Kabwe,Kafue,Kalabo,Kalomo,Kalulushi,Kaoma,Kapiri Mposhi,Kaputa,Kasama,Kasempa,Katete,Kawambwa,Kazungula,Kitwe,Livingstone,Luangwa,Luanshya,Lufwanyama,Lukulu,Lundazi,Lusaka,Luwingu,Mambwe,Mansa,Masaiti,Mazabuka,Mbala,Milenge,Mkushi,Mongu,Monze,Mpika,Mpongwe,Mporokoso,Mpulungu,Mufulira,Mufumbwe,Mumbwa,Mungwi,Mwense,Mwinilunga,Nakonde,Namwala,Nchelenge,Ndola,Nyimba,Petauke,Samfya,Senanga,Serenje,Sesheke,Shangombo,Siavonga,Sinazongwe,Solwezi,Zambezi");
$states['Zimbabwe'] = construct_array("Beitbridge,Bikita,Bindura,Binga,Bubi,Buhera,Bulawayo,Bulilima,Centenary,Chegutu,Chikomba,Chimanimani,Chipinge,Chiredzi,Chirumhanzu,Chitungwiza,Chivi,Epworth,Gokwe North,Gokwe South,Goromonzi,Guruve,Gutu,Gwanda,Gweru,Harare Rural,Harare Urban,Hurungwe,Hwange,Insiza,Kadoma,Kariba,Kwekwe,Lupane,Makonde,Makoni,Mangwe (South),Marondera,Masvingo,Matobo,Mazowe,Mberengwa,Mount Darwin,Mudzi,Murehwa,Mutare,Mutasa,Mutoko,Mwenezi,Nkayi,Nyanga,Rushinga,Seke,Shamva,Shurugwi,Tsholotsho,Umguza,UMP,Umzingwane,Wedza,Zaka,Zvimba,Zvishavane");
ksort($states);


/* Data Population Count
// print_p($countries);
$new_states = array();
$my_status = array_merge($new_states, $states);
//print_p($my_status);
$i = 0;
foreach($my_status AS $arr=>$v) {
    $y = count($v);
    //print_p($y);
    $i= $i+$y;
}
print_p($i);
*/
// Total Countries Covered: 250 Countries ( With the Geo Class )
// Total States Covered: 6,832 States.
