<?php
/*-------------------------------------------------------+
| PHP-Fusion Content Management System
| Copyright (C) PHP-Fusion Inc
| https://www.php-fusion.co.uk/
+--------------------------------------------------------+
| Filename: login/locale/English/user_gauth.php
| Author: PHP-Fusion Development Team
+--------------------------------------------------------+
| This program is released as free software under the
| Affero GPL license. You can redistribute it and/or
| modify it under the terms of this license which you
| can read by viewing the included agpl.txt or online
| at www.gnu.org/licenses/agpl.html. Removal of this
| copyright header is strictly prohibited without
| written permission from the original author(s).
+--------------------------------------------------------*/

$locale['uf_gauth'] = "Google 2-Step Authenticator";
$locale['uf_gauth_desc'] = "2 Factor Authentication using Google Authenticator.";

$locale['uf_gauth_100'] = "Two-Step Verification";
$locale['uf_gauth_101'] = "This User Account is secured with a Two-Step Verification";
$locale['uf_gauth_102'] = "Please enter the verification code generated by your Google Authenticator application.";
$locale['uf_gauth_103'] = "Authentication Code";
$locale['uf_gauth_104'] = "You need to provide a valid Authentication Code";
$locale['uf_gauth_105'] = "Enter Google Authentication Code";
$locale['uf_gauth_106'] = "Verify Code";
$locale['uf_gauth_107'] = "Deactivate Code";
$locale['uf_gauth_108'] = "Enable Two-Step Authentication Code";
$locale['uf_gauth_109'] = "No, I do not want to use 2-Step Authentication";
$locale['uf_gauth_110'] = "Yes, I wish to enroll 2-Step Authentication";
$locale['uf_gauth_111'] = "Your PHP Fusion account been protected with Google Authenticator. Google Authenticator is a secure, easy to use, two-factor authentication application for your mobile device that is immune from replay-attacks, man-in-the-middle attacks, and a host of other thread vectors.";
$locale['uf_gauth_112'] = "Your account have been secured with the Two-Step Authentication.";
$locale['uf_gauth_113'] = "Please make sure you do not remove the pairing on your app before deactivating on your user account. You will need it to deactivate the Two-Step Authentication on this user account.";
$locale['uf_gauth_114'] = "Deactivate the Two-Step Authentication by entering the passcode below:";

$locale['uf_gauth_115'] = "Activating Two-Step Authentication";
$locale['uf_gauth_116'] = "Once you complete this process, you will never be shown the setup information again. If you wish, you can print this information and keep it in a secure location.";

$locale['uf_gauth_120'] = "Your account has been suspended at {SITE_NAME} due to security reason.";
$locale['uf_gauth_121'] = "Account Suspended due to Suspicious Account Activity";
$locale['uf_gauth_122'] = "Dear {USERNAME},<br/><br/>We have recently find that there was multiple attempts to login into your user account at {SITENAME}. And as a security measure, we have temporarily [strong]suspended the account[/strong]. If you feel that there was an error to this, you can restore your account with the link below.<br/><br/>{RESTORE_LINK}<br/><br/>Your regards,<br/>{SITE_ADMIN}<br/>Site Administrator,<br/>{SITENAME}";
$locale['uf_gauth_123'] = "We could not verify your authentication code. You have {D} attempt(s) left";

$locale['uf_gauth_130'] = "Your account has been successfully restored.";
$locale['uf_gauth_131'] = "We could not restore your account due to an invalid restore code. Please contact the site administrator.";
$locale['uf_gauth_132'] = "Sorry, we could not find the user account. Please contact the site administrator.";

$locale['uf_gauth_140'] = "You have successfully activated the Two Step Authentication login on your user account.";
$locale['uf_gauth_141'] = "Your code is invalid and failed to be authenticated. Please try again.";
$locale['uf_gauth_142'] = "You have successfully deactivated the Two Step Authentication login on your user account.";
$locale['uf_gauth_143'] = "Your code failed to be authenticated. Please try again.";

$locale['uf_gauth_150'] = "Two-Step Authentication requires the Google Authenticator App.";
$locale['uf_gauth_151'] = "Scan the barcode or enter this information:";
$locale['uf_gauth_152'] = "Account Name:";
$locale['uf_gauth_153'] = "Your Secret Key:";
$locale['uf_gauth_154'] = "Use your Google Authenticator app to scan this QR code and enter the one time password below.";
$locale['uf_gauth_155'] = "Verify that the pairing was successful by entering the passcode below:";

$locale['uf_gauth_156'] = "Install the Google Authenticator app on your mobile device:";
$locale['uf_gauth_157'] = "iPhone, iPad, or iPod Touch:";
$locale['uf_gauth_158'] = "Visit the App Store and search for Google Authenticator.";
$locale['uf_gauth_159'] = "Android:";
$locale['uf_gauth_160'] = "Visit Google Play and search for Google Authenticator.";
$locale['uf_gauth_161'] = "Blackberry:";
$locale['uf_gauth_162'] = "Visit <a href='www.m.google.com/authenticator'>www.m.google.com/authenticator</a> on your web browser.";
